---
title: "Nuevas tecnologías para el análisis astadístico de datos"
subtitle: 'Git & GitHub'
author: "Natalia da Silva (natalia@iesta.edu.uy, @pacocuak)"
date: ""
output:
  xaringan::moon_reader:
    css: ["myslides", "rladies-font.css"]
    self_contained: false
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

# Git es...

- Git es uns sistema de control de versionado originalmente diseñado para ayudar a grupos de desarrolladores a hacer trabajo colaborativo en
proyectos grandes de desarrolo de software.

- Git ha sido tomado por la comunidad de ciencia de datos redefiniendo el proposito. Lo usamos para manejar la colección de archivos que hacen a un proyecto.
<!-- datos, figuras, reportes, codigo fuente -->
---

# Porqué GitHub? 

- Brinda un lugar en internet para tu proyecto basado en Git.

- Es un canal de distribución para manejar tu proyecto de Git.

- Colaborar, otras personas puden ver el proyecto, sincronizarlo con el tuyo y hacer cambios.

---

# Que necesitamos

- Installar Git

- Conectar Git con GitHub

- Lograr que RStudio se comunique con Git y GitHub

---

# Que hacer

- Dedicar una carpeta para cada proyecto.

- Que el proyecto sea de RStudio.

- Hacer un repositorio nuevo de Git.

- Trabajar en el proyecto y en vez de salvar hago `commit`.

- `push`  el  `commit` al repositorio de GitHub.

---

# Que ganamos

- Mostrar tu trabajo publicamente
<!-- - La gente puede ver tu trabajo si el repositorio es público usar tu código pueden clonar o forkear el repositorio -->

- Seguir de cerca proyectos interesantes
<!-- - Si te interesa algún proyecto de otro podes tener notificaciones de actualizaciones o forkear el repositorio -->

- Colaboradores predeterminados y hasta externos
---

# Especiales de GitHub

- **Issues**
 Es una lista de cosas, bugs, pedidos de cambios, comentarios, etc.  
Integrados con emails, pueden asignarse a personas y ver el progreso.  
Integrado con los `commits` permite registrar que los cambios de un commit resuelven el problema.  

- **Pull requests**
Permite que un proyecto tenga múltiples ramas de desarrollo independiente.
Algunas ramas pueden pegarse a la versión de desarrollo original.

 Un "pull request" es una propuesta formal de proponer cambios puede estar relacionados a la solucion de un problema (issue).
---


# Actividad grupos


---


