---
title: "Resultados formulario Google"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r libs, echo = FALSE, warning = FALSE, message = FALSE }
library(tidyverse)
library(here)
library(lubridate)
```

<!-- # calcedad <- function(cumple, hoy=dmy("10/03/2018")) { -->
<!-- # require(lubridate) -->
<!-- #  -->
<!-- #     period <- time_length( interval(cumple, hoy), unit="year") -->
<!-- #  -->
<!-- #     round(period) -->
<!-- # } -->
```{r datatr, message =  FALSE, warning = FALSE}


data <- read_csv( here::here( "googleform",  "stat_ntform.csv" ) )

data_cl <- data %>% 
  select(-X12)%>%
  set_names( nm = c("marca", "nombre", "email", "nacimiento", "hstrabaja", "udelarmatr", "estmatr", "materias","compu", "so", "compuclass","user", "interes", "ds") ) %>%
  filter(materias != "Probabilidad") %>% 
  mutate(genero = factor(c("M", "F", "F", "F", "F", "M", "F", "M", "M", "F", "F", "M", "F", "F", "M", "M", "M" ,"M"))) %>%
   mutate(edad = time_length( interval(dmy(nacimiento), today()), unit="year"))%>%
  mutate(labhstrabaja = factor(hstrabaja, labels = c("[10-20)","[20-30)", "[30-40)", "Menos de 10", "No trabaja" ))) %>% 
  mutate(labhstrabaja = factor(labhstrabaja, levels = levels(labhstrabaja)[c(5,4,1,2,3)])) %>%
  mutate(labuser=factor(user,  labels =c("[1-3)", "[3-5)", "Menos de 1 año", "No lo uso")))%>%
  mutate(labuser= factor(labuser, levels= levels(labuser)[c(4,3,1,2)]))



```

```{r,message=FALSE,warning=FALSE}
data_cl %>% ggplot(aes(x = "", y = edad)) + 
  geom_boxplot() + labs(y = "Edad ", x = "", title = "Diagrama de caja con la edad en años de los estudiantes de STAT_NT 2018") 


```

```{r,message=FALSE,warning=FALSE}
data_cl %>% ggplot(aes(udelarmatr)) + 
  geom_histogram() + labs(y = "Estudiantes ", x = "", title = "Histograma de año de matriculación a la UDELAR") 


```


```{r,message=FALSE,warning=FALSE}
data_cl %>% ggplot(aes(estmatr)) + 
  geom_histogram() + labs(y = "Estudiantes ", x = "", title = "Histograma de año de matriculación a la Lic. en Estadística")

```
```{r viz,message=FALSE,warning=FALSE}

data_cl %>% 
  ggplot() +  geom_bar(aes(x =genero, fill = genero)) +
  scale_fill_brewer(palette = "Dark2") 

```

```{r, message=FALSE, warning=FALSE}

data_cl %>% 
  ggplot() + geom_bar(aes( x = genero, y = (..count..)/sum(..count..), fill = genero)) +
       scale_y_continuous(labels=scales::percent)+
scale_fill_brewer(palette = "Dark2") +
    geom_text(aes( x = genero,label = scales::percent((..count..)/sum(..count..)),
                   y= (..count..)/sum(..count..)), stat= "count", vjust = -.5) + labs(x = "Género", y = "Porcentaje", fill = "Género", title = "Porcentaje de estudiantes en STAT_NT por género") 
  


```


```{r, message = FALSE, warning = FALSE}

data_cl %>% 
  ggplot() + geom_bar(aes( x = labhstrabaja, y = (..count..)/sum(..count..), fill =  labhstrabaja)) +
       scale_y_continuous(labels=scales::percent)+
scale_fill_brewer(palette = "Dark2") +
    geom_text(aes( x = labhstrabaja,label = scales::percent((..count..)/sum(..count..)),
                   y= (..count..)/sum(..count..)), stat= "count", vjust = -.5) + labs(x = "Horas semanales", y = "Porcentaje", fill = "Horas semanales", title = "Porcentaje de estudiantes en STAT_NT según horas que trabaja a la semana") +
  theme(axis.text.x = element_text(angle = 90))

```



```{r, message = FALSE, warning = FALSE}

data_cl %>% 
  ggplot() + geom_bar(aes( x = labuser, y = (..count..)/sum(..count..), fill =  labuser)) +
  scale_y_continuous(labels=scales::percent)+
scale_fill_brewer(palette = "Dark2") +
    geom_text(aes( x = labuser,label = scales::percent((..count..)/sum(..count..)),
                   y= (..count..)/sum(..count..)), stat= "count", vjust = -.5) + labs(x = "Años como usario de R", y = "Porcentaje", fill = "Anños de uso", title = "Porcentaje de estudiantes en STAT_NT según años que usa R ") +
  theme(axis.text.x = element_text(angle = 90))

```