\documentclass[12pt]{article}
\usepackage{enumitem}
\usepackage{amsmath}
\usepackage{amsfonts}
\usepackage{amssymb}
\usepackage{makeidx}
\usepackage{graphicx}
\usepackage{float}
\usepackage[table]{xcolor}
\usepackage{tikz}
 \usepackage{pgf}
\usepackage[utf8]{inputenc}

% margins
\usepackage[margin=3cm]{geometry}
\parskip         7.2pt   % sets spacing between paragraphs
\parindent         0pt   % sets leading space for paragraphs


\begin{document}


\title{Análisis Predictivo}
\author{IESTA}
\date{}
\maketitle

\section{Objetivo}
El objetivo de este trabajo es realizar la experimentación de un modelo predictivo capaz de detectar aquellos alumnos, \textbf{pertenecientes a primero de CES}, que tengan una alta probabilidad de abandonar el sistema educativo público en el año siguiente. Con este propósito se va a utilizar información de la transición de dichos alumnos entre los años 2016 y 2017.

\subsection{Población de estudio}
La población que se va a analizar son los \textbf{estudiantes de primero de CES que cursan primero en el año 2016}. Dicha población se compone de una matrícula de 40.293 alumnos, que pertenecen a 254 centros educativos de educación media pública.\\


`
<<libs, warning=FALSE,message=FALSE,echo=FALSE>>=
library(tidyverse)
library(here)
library(maptools)
library(raster)
library(ggplot2)
library(rgdal)
library(dplyr)
library(ggmosaic)

@

<<data,  warning=FALSE,message=FALSE, echo=FALSE>>=

load(here::here("data", "PredictiveBase16_17.RData"))
load(here::here("data", "CobStats2.RData"))

@



\begin{table}[H]
	\centering
	\begin{tabular}{||c||c|c|}
		\hline 
		\rule[-1ex]{0pt}{2.5ex} \cellcolor[rgb]{ .663,  .816,  .557} Matrícula 2016 & \cellcolor[rgb]{ .663,  .816,  .557} ANEP* & \cellcolor[rgb]{ .663,  .816,  .557} CEIBAL (UE)** \\ 
		\hline 
		\rule[-1ex]{0pt}{2.5ex} 1ero CES-Ciclo básico &  & 40.293 \\ 
		\hline 

	\end{tabular} 
	\caption{Cantidad de Matriculados.}
	\label{Matricula}
\end{table}



\scriptsize{\textit{* Fuente: Monitor Liceal CES (Incluye Ref. 2006; Plan 1996 Extraedad; Plan Ciclo B?sico 2009; Ad. Plan 09 semi-presencial; Plan 2012 CB Extraedad-Propuesta 2016 )Ref 2006 + Ref 2006 CB Rural )= 107.392 ; (0tros Planes) = 15.374\\
**Fuente: CRM}}

\vspace{2cm}
\normalsize



\newpage

\section{Analisis descriptivo}

El primer análisis exploratorio que se va a realizar tiene como objetivo describir las variables disponibles. Encontrar la relación entre las mismas y evaluar cuales son las que tienen mayor impacto en el abandono.


\subsection{Descripción del set de datos}

Se va a utilizar la base de datos \textbf{Predic\_16\_17}. La misma reúne información que proviene de diferentes fuentes, las cuales se detallan a continuación: 

\begin{itemize}
\item \textbf{\underline{Marco Uruguay Estudia 2016}}, de ahora en m?s \textbf{Marco UE 2016}. Este set de datos tiene información correspondiente a cada uno de los alumnos matriculados en CES en el a?o 2016. La misma se conforma por el centro educativo al cuál esta concurriendo el alumno, departamento al que pertenece dicho centro, grado del alumno y grupo. 


\item \textbf{\underline{Marco Uruguay Estudia 2017}}, de ahora en más \textbf{Marco UE 2017}. Este set de datos tiene la información de la matrícula de CES del a?o 2017. Dicha información es de suma importancia para investigar la transición educativa de los alumnos entre 2016 y 2017. Uno de los aspectos claves fue detectar cuantos alumnos matriculados en el \textbf{Marco UE 2016} se encuentran registrados en el \textbf{Marco UE 2017}.

\item \textbf{\underline{Pasaje de lista en linea proporcionado por Uruguay Estudia}}, de ahora en más \textbf{Marcas UE 2016}. Este set de datos tiene la información del pasaje de lista en linea por parte de Uruguay Estudia. Para este análisis se van a tomar en cuenta 57 días, desde el 28 de marzo de 2016 hasta el 24 de junio de 2016 (la semana antes de las vacaciones de Julio).


\item \textbf{\underline{Análisis de la trayectoria del alumno desde 2013 hasta 2016}} proporcionada por CRM, de ahora en más \textbf{Trayectorias}. Dicho set de datos tiene el seguimiento académico de los estudiantes, es decir los grados cursados desde 2013 hasta 2016. También la fecha de nacimiento de cada uno de los alumnos (dicha información es de relevancia para calcular si el alumno tienen extra-edad).


\item \textbf{\underline{Contexto sociocultural del liceo}}, de ahora en más \textbf{Contextos}. Esta información fue creada en un trabajo anterior (por parte de Ceibal y el IESTA) en el cual se experimentoó una metodologiía para estimar el contexto de los liceos.

\end{itemize}   


En el cuadro \ref{tab:VAR} de la sección \ref{VD} se va a detallar las variables utilizadas de cada conjunto de datos mencionados. Las mismas se reúnen en el set de datos \textbf{Predic\_16\_17.RData}.



\subsubsection{Variables disponibles} \label{VD}
\begin{table}[H]
	\centering
	
	\begin{tabular}{|c|c|c|}
		\hline
	\rowcolor[rgb]{ .776,  .878,  .706}	Variable &  Descripción &   Fuente \\
		\hline
		documento & Cédula de Identidad del alumno & \textbf{Marco UE 2016} \\
		\hline
		nro\_doc\_centro\_educ & Liceo que concurre el alumno en 2016 & \textbf{Marco UE 2016} \\
		\hline
		nombre\_departamento & Nombre del Departamento del centro educativo & \textbf{Marco UE 2016} \\
		\hline
		grupo\_desc & Grupo del alumno en 2016 & \textbf{Marco UE 2016} \\
		\hline
		coberturaT & Cobertura en el primer semestre de 2016  & \textbf{Marcas UE 2016} \\
		\hline
		Centro\_Grupo & Liceo y grupo del alumno en 2016 & \textbf{Marco UE 2016} \\
		\hline
		cl    & Cluster - contexto sociocultural del liceo en 1016 & \textbf{Contextos} \\
		\hline
		Grado\_2016\_UE & Grado del alumno en el 2016 según UE & \textbf{Marco UE 2016} \\
		\hline
		Grado2013 & Grado del alumno en 2013 según CRM & \textbf{Trayectorias} \\
		\hline
		Grado2014 & Grado del alumno en 2014 según CRM & \textbf{Trayectorias} \\
		\hline
		Grado2015 & Grado del alumno en 2015 según CRM & \textbf{Trayectorias} \\
		\hline
		Grado 2016 & Grado del alumno en 2016 según CRM & \textbf{Trayectorias} \\
		\hline
		Sexo  & Sexo del alumno & \textbf{Trayectorias}  \\
		\hline
		Fecha.nacimiento & Fecha de nacimiento del alumno & \textbf{Trayectorias} \\
		\hline
		Grupo\_UE\_2017 & Grupo del alumno en 2017 & \textbf{Marco UE 2017} \\
		\hline
		inasistencias & cantidad de inasistencias en el primer semestre de 2016 & \textbf{Marcas UE 2016} \\
		\hline
		asistencias & cantidad de asistencias en el primer semestre de 2016 & \textbf{Marcas UE 2016} \\
		\hline
	\end{tabular}%
	\caption{Variables de 
	\label{tab:VAR}%
	\textbf{Predic\_16\_17.RData}}
\end{table}%

A partir de dichas variables disponibles, se construyeron otras, las mismas se detallan a continuación:

\begin{itemize}
\item \textbf{Extra-edad Leve}: Se considera que el alumno tiene extra-edad leve cuando nace antes del 30 de abril de 2003 . Es decir un año más de la edad normativa para dicha generación.

\item \textbf{Extra-edad Fuerte}: Se considera que el alumno tiene extra-edad fuerte cuando nace antes del 30 de abril de 2002. Es decir dos años más de la edad normativa para dicha generación.

\item \textbf{Inasistencias relativas}: Se calculan como el total de inasistencias del alumno sobre el total de veces que se le paso lista (en los 57 d?as considerados). Por ejemplo si a un alumno le pasaron lista 40 veces de las cuales 20 no asisití al centro, su inasistencia relativa es 20/40=0.5 (asistí a la mitad de los días que se le paso lista).


\item \textbf{Abandono:} Esta variable hace referencia a aquellos alumnos matriculados en el \textbf{Marco UE 2016} que en el 2017 no están anotados en el sistema de educación pública en el \textbf{Marco UE 2017}.\textbf{Es necesario aclarar que los mismos no necesariamente abandonaron la educación, puede ser que están anotados en el sistema privado. En este contexto cuando se menciona abandono se hace referencia a el sistema educativo público}

\end{itemize}


\newpage
\subsection{Matrícula 2016 según departamento}

La matrícula de primero de CES, conformada por 40.233 estudiantes, que pertenecen a diferentes departamentos del Uruguay. Dicha composición se puede observar en el cuadro \ref{tab:Dep}.

<<mapauy, warning=FALSE,message=FALSE,echo=FALSE>>=
uruguay <- getData("GADM", country = "UY", level = 0)

uruguay_states <- getData("GADM", country = "UY", level = 1)

uystates_UTM <-spTransform(uruguay_states, CRS("+init=EPSG:5383")) 
NAME_1 <- uystates_UTM@data$NAME_1
count <- as.numeric(table(Predic_16_17$nombre_departamento))   #or any other data you can associate with admin level here

count_df <- data.frame(NAME_1, count)

uystates_UTM@data$id <- rownames(uystates_UTM@data)
uystates_UTM@data <- plyr::join(uystates_UTM@data, count_df, by="NAME_1")
uystates_df <- fortify(uystates_UTM)
uystates_df <- plyr::join(uystates_df,uystates_UTM@data, by="id")


theme_opts <- list(theme(panel.grid.minor = element_blank(),
                       panel.grid.major = element_blank(),
                       panel.background = element_blank(),
                       plot.background = element_blank(),
                       axis.line = element_blank(),
                       axis.text.x = element_blank(),
                       axis.text.y = element_blank(),
                       axis.ticks = element_blank(),
                       axis.title.x = element_blank(),
                       axis.title.y = element_blank(),
                       plot.title = element_blank()))
@

\begin{figure}[h]
\begin{center}
<<pl, warning=FALSE, message=FALSE,echo=FALSE>>=
ggplot() + 
  geom_polygon(data =uystates_df, aes(x = long, y = lat, group = group, fill =
                                       count), color = "black", size = 0.25) +
  theme(aspect.ratio=1)+
  scale_fill_gradient2(trans="log", breaks= c(1e2, 1e3, 1e4), midpoint = log(1e3)) +
  theme_opts 
@
\caption{Composición de la matrícula 2016 de primer año de CES según departamento}
\end{center}
\end{figure}

EL MAPA SUPLANTA LA TABLA \ref{tab:Dep}

\begin{table}[H]
	\centering
	\begin{tabular}{|c|c|c|c|}
		\hline
	\rowcolor[rgb]{ .776,  .878,  .706}	Departamento & Cantidad de alumnos & Departamento & Cantidad de alumnos \\
		\hline
		Artigas & 1.139  & Paysandu & 1.514 \\
		\hline
		Canelones & 7.143  & Rio Negro & 745 \\
		\hline
		Cerro Largo & 1.098  & Rivera & 1.889 \\
		\hline
		Colonia & 1.487  & Rocha & 1.070 \\
		\hline
		Durazno & 654   & Salto & 1.759 \\
		\hline
		Flores & 367   & San José & 1.406 \\
		\hline
		Florida & 885   & Soriano & 1.204 \\
		\hline
		Lavalleja & 834   & Tacuarembo & 1.545 \\
		\hline
		Maldonado & 2.123  & Treinta y Tres & 711 \\
		\hline
		Montevideo & 12.660 & Total & 40.233 \\
		\hline
	\end{tabular}%
	\caption{Composición de la matrícula según departamento}
	\label{tab:Dep}%
\end{table}%

\subsection{Trnasición educativa entre 2016-2017}
En esta sección se va a estudiar la transición educativa de los 40.233 alumnos matriiculados en primero de CES en 2016 \footnote{60 alumnos no se tuvieron en cuenta ya que si estaban en el set de datos \textbf{Marco UE 2016} pero no se encontraron en el set de datos \textbf{Trayectorias}}, de forma tal de observar en que situación se encuentran en 2017. En el cuadro \ref{tab:Abandono} se muestra la cantidad de alumnos que estaban cursando primero de CES en 2016 y en 2017 no se anotaron en el sistema de educación pública.

\begin{figure}[h]
\begin{center}
<<abandono, warning=FALSE,message=FALSE,echo=FALSE, fig.height=5, fig.width=6>>=

Predic_16_17 %>% mutate(Abandono = factor(Abandono, labels = c("No", "Si"))) %>% 
  ggplot() + geom_bar(aes( x = Abandono, y = (..count..)/sum(..count..), fill = Abandono)) +
       scale_y_continuous(labels=scales::percent)+
scale_fill_brewer(palette = "Dark2") +
    geom_text(aes( x = Abandono,label = scales::percent((..count..)/sum(..count..)),
                   y= (..count..)/sum(..count..)), stat= "count", vjust = -.5) + labs(x = "Abandono", y = "Porcentaje", fill = "Abandono") 
@
\caption{Porcentaje de abandono de 2016 a 2017}
\end{center}
\label{propaba}
\end{figure}
GRAFICO DE BARRAS REMPLAZA TABLA \ref{tab:Abandono}


\begin{table}[H]
	\centering
	\begin{tabular}{|c|c|c|}
		\hline
\rowcolor[rgb]{ .776,  .878,  .706}		No Abandona & Abandona & Total \\
		\hline
		37.535 & 2.698 & 40.233 \\
		\hline
		93,0\% & 7,0\% & 100,0\% \\
		\hline
	\end{tabular}
	\caption{Cantidad de alumnos de la matriculados que abandonaron de 2016 a 2017}
	\label{tab:Abandono}
\end{table}

El 93\% de los alumnos siguen anotados en el sistema de educación pública en el 2017, mientras que del 7\% restante no se encontraron registros de inscripción en dicho sistema. \textbf{Recordar que los mismos no necesariamente abandonaron la educación, puede ser que están anotados en el sistema privado}.



El 93\% de la matrícula que sigue en el sistema educativo público en el 2017 se anotaron en diferentes grados, en el cuadro \ref{Destino} se detalla cuál fue el destino de esos estudiantes. 

\begin{table}[H]
	\centering
	\begin{tabular}{|c|c|c|c|c|}
		\hline
\rowcolor[rgb]{ .776,  .878,  .706}		1?    & 2?    & CBT   & FPB   & Total \\
		\hline
		7.450 & 28.786 & 348   & 951   & 37.535 \\
		\hline
		19,8\% & 76,7\% & 0,9\% & 2,5\% & 100\% \\
		\hline
	\end{tabular}
	\label{tab:addlabel}
	\caption{Destino de alumnos que siguen matriculados desde 2016 a 2017}
	\label{Destino}
\end{table}

GRAFICO DE BARRAS REMPLAZA TABLA \ref{Destino}
\begin{figure}[h]
\begin{center}
<<destinos, warning = FALSE, message = FALSE, echo = FALSE, fig.height = 5, fig.width = 6>>=
Predic_16_17 %>% mutate(G17 = substr(Grupo_UE_2017,1,3)) %>%
  dplyr::filter(!is.na(G17) ) %>%
  mutate(G17 = factor(G17, labels = c("1ro", "2do","CBT","FPB"))) %>%
  ggplot() + geom_bar(aes( x = G17, y = (..count..)/sum(..count..), fill = G17)) + scale_y_continuous(labels =scales::percent)+
scale_fill_brewer(palette = "Dark2") +
    geom_text(aes( x = G17,label = scales::percent((..count..)/sum(..count..)), y = (..count..)/sum(..count..)), stat = "count", vjust = -.5) + labs(x = "Destinos", y = "Porcentaje", fill = "Destino" )
@
\caption{Porcentaje de alumnos por destino que siguen matriculados desde 2016 a 2017 }
\end{center}
\end{figure}


El 76,7\% de los alumnos que siguen matriculados pasan a segundo grado de CES, mientras que el 19,8\% cursan nuevamente primero. Hay una pequé a proporción de alumnos que se anotan en CBT (Ciclo Básico Tecnológico) y otra pequé a porción en FPB (Formación Profesional Básica).\\

\vspace{2cm}
\subsection{Análisis de la cobertura del pasaje de lista en línea}
El primer análisis que se va a realizar es evaluar que todos los grupos tengan una cobertura homogénea, es decir que a los alumnos del mismo grupo le pasen la lista la misma cantidad de días.

Para esto se creo una variable que se llama \textbf{Predominio}. La misma es el porcentaje más grande de alumnos (del mismo grupo) que tienen la misma cobertura. Es decir si a un grupo X al 90\% de los alumnos le pasan 20 veces la lista, al 5\% le pasan 15 veces y al 5\% restante le pasan solo una vez, la variable \textbf{Predominio} tiene el valor 90\% (el porcentaje más grande de alumnos con la misma cobertura), en el gráfico \ref{fig:pred} se ilustra el comportamiento de dicha variable para cada uno de los grupos en un histograma.

% \begin{figure}[H]
% 	\centering
% 	\includegraphics[width=0.7\linewidth]{Cobertura}
% 	\caption{Predominio de la cobertura}
% 	\label{fig:pred}
% \end{figure}

\begin{figure}[h]
\begin{center}
<<r, warning = FALSE, message = FALSE, echo = FALSE, fig.width = 5, fig.height = 5>>=
ggplot(COB_stats2, aes(x=Predominio, y=..density..)) +
  geom_histogram(bins = 30,col="grey")+
  labs(x = "Frecuencia",y="Densidad")
@
\caption{Máxima frecuencia de la cobertura por grupo}
\end{center}
\end{figure}

Lo esperable es que todos los alumnos del grupo tengan la misma cobertura es decir que el predominio sea 100\%. Hay 560 grupos que cumplen con el valor esperado los mismos están representados en la barra más contra la derecha en el histograma.

Si bien no todos los grupos están en la situación ideal, en el histograma queda representado que en la mayoría de los grupos, más del 80\% de sus alumnos tienen la misma cobertura.

Hay 1.437 grupos (de un total de 1.513, es decir un 95\%) en el que el 80\% o más de los alumnos tiene la misma cobertura. Por lo que se concluye que la cobertura a nivel de grupos es ``aceptable''. En lo que sigue del análisis se va tomar en cuenta  dicho 95\% de los grupos que tienen una cobertura intra-grupos homogénea, dichos grupos tienen 37.849 alumnos. 

Se va a analizar como es la \textbf{cobertura} del pasaje de lista en linea, la misma no es igual para todos los centros, es decir hay algunos que tienen mayor cobertura que otros. 

En el gráfico \ref{fig:cobertura} se realiza un boxplot de la variable cobertura en los 57 días que se está evaluando. La misma se realizó para el 95\% de los grupos que tienen una cobertura intra-grupos homogénea.

\begin{figure}[h]
\begin{center}
<<warning=FALSE, echo=FALSE,message=FALSE,fig.width=4,fig.height=4>>=
centro <-  COB_stats2 %>% filter(Predominio>=0.80) %>% dplyr::select(Centro_Grupo)
Predic_16_17 %>% mutate(Centro_Grupo, factor(Centro_Grupo))%>%
  filter(Centro_Grupo %in% centro[,1]) %>%
  ggplot(aes(x = "", y = coberturaT)) + geom_boxplot()

@
\caption{Cobertura del pasaje de lista en linea}
	\label{fig:cobertura}
	\end{center}
\end{figure}

% \begin{figure} [H]
% 	\centering
% 	\includegraphics[width=0.5\linewidth]{cobertura2}
% 	\caption{Cobertura del pasaje de lista en linea}
% 	\label{fig:cobertura}
% \end{figure}

Los nivele de cobertura, para dicha población, son buenos. Como se representa en el boxplot de la figura \ref{fig:cobertura}, al 75\% de los alumnos pertenecientes a dicha población se le pasó 47 días o más la lista (de los 57 días en los que se está analizando). Por lo que se entiende que es una buena cobertura para realizar el análisis.\\ 

Para realizar el modelo se van a tomar los grupos que tienen una cobertura homogénea (es decir aquellos que más del 80\% de los alumnos del grupo tienen la misma cobertura) y ademas que dicho valor supere los 47 días. En esta situación hay 28.232 alumnos (que pertenecen a 1.095 grupos diferentes). En lo que resta de este análisis se va a trabajar con esa población de estudio.


\section{Analisis exploratorio de las covariables}\label{cap3}

\subsubsection{Selección de la población de estudio}
\textbf{Se utilizará una porción de la totalidad de los estudiantes matriculados en primero de CES en 2016}. Un factor importante a la hora de evaluar el abandono, el cuál se observa en el análisis exploratorio, son las inasistencias del alumno. Por lo que se entiende que la cobertura del pasaje de lista en linea (de los estudiantes analizados) tiene que ser buena.

Por esta razán el criterio para la elección de los estudiantes, con los que se va a inferir el modelo predictivo, es seleccionar aquellos que tengan una buena cobertura de pasaje de lista en linea.\\

Como se expuso en el análisis descriptivo de un total de 1.513 grupos, hay 1.437 (el 95\%) que tienen una cobertura homogenea (es decir, todos los alumnos del grupo tienen la misma cobertura). De dichos grupos 1.095 tienen una cobertura mayor a 47 días. Los mismos están compuestos por 28.232 alumnos y son los que se van a considerar en el análisis predictivo.\\ 

SAQUE LA FIGURA DE SELECCION DE GRUPOS PARA INCLUIR EN EL MODELO PREDICTIVO PORQUE NO DICE NADA
% 
% \begin{figure}[H]
% 	\centering
% 	\begin{tikzpicture}[thick]
% 	\draw (4,-3) rectangle (-2,2) node[below right] {1.513 grupos};
% 	\draw (1,-0.5) [fill=cyan]  circle (1.8) node[above,shift={(0.4,0.7)}] {};
% 	\draw (1,-0.5) circle (2.3) node[above,shift={(0,1.8)}] {};
% 	\node at (1,1.4) {1.437 grupos};
% 	\node at (1.1,-.4) {1.095 grupos};
% 	%\node at (1.1,-.8) {28.566 alumnos};
% 	\end{tikzpicture}
% 	\caption{Selecci?n de grupos para incluir en el modelo predictivo}
% 	%\label{fig:Selec}
% \end{figure}


Primero se va a evaluar como es la transición entre 2016 y 2017 para dicha población, es decir cuantos alumnos abandonan y cuantos siguen matriculados en 2017.\\

\begin{table}[H]
	\centering
	\begin{tabular}{|c|c|c|}
		\hline
		\rowcolor[rgb]{ .776,  .878,  .706}		No Abandona & Abandona & Total \\
		\hline
		26.566 & 1.666 & 28.232 \\
		\hline
		94,0\% & 6,0\% & 100,0\% \\
		\hline
	\end{tabular}%
	\caption{Cantidad de alumnos de la matrícula que abandonaron de 2016 a 2017}
	\label{tab:Abandono2}%
\end{table}%

ESTA FIGURA REMPLAZA \ref{tab:Abandono2}

\begin{figure}[h]
\begin{center}
<<datpr, echo=FALSE, warning = FALSE, message = FALSE, fig.height = 5, fig.width = 6>>=

Cg <- COB_stats2 %>% filter(Predominio>0.8 & CobPred>47) %>% dplyr::select(Centro_Grupo) 

Predic_16_17 %>% filter(Centro_Grupo%in%factor(Cg[,1])) %>% filter(coberturaT>47)  %>% 
  mutate(Abandono = factor(Abandono) ) %>% ggplot() + geom_bar(aes( x = Abandono, y = (..count..)/sum(..count..), fill = Abandono)) + scale_y_continuous(labels=scales::percent)+
scale_fill_brewer(palette = "Dark2") +
    geom_text(aes( x = Abandono,label = scales::percent((..count..)/sum(..count..)), y = (..count..)/sum(..count..)), stat = "count", vjust = -.5) + labs(x = "Abandono", y = "Porcentaje", fill = "Abandono" )

@
\caption{Porcentaje de alumnos de la matrícula que abandonaron de 2016 a 2017 dentro de los que tienen cobertura homogenea y cuayo valor supere los 47 días}
\end{center}
\label{propabasub}
\end{figure}

La proporción de alumnos que abandonan y los que no, tiene un comportamiento muy similar al de la matrícula total mostrada previamente en la Figura \ref{propaba}.

% 
% TABLA \ref{Aband2}
% \begin{table}[H]
% 	\centering
% 	\begin{tabular}{|c|c|c|}
% 		\hline
% 		\rowcolor[rgb]{ .776,  .878,  .706}		No Abandona & Abandona & Total \\
% 		\hline
% 		37.535 & 2.698 & 40.233 \\
% 		\hline
% 		93,0\% & 7,0\% & 100,0\% \\
% 		\hline
% 	\end{tabular}%
% 	
% 	\caption{Cantidad de alumnos de la matr?cula que abandonaron de 2016 a 2017}
% 	\label{tab:Aband2}%
% \end{table}%

EL MOSAIC PLOT REMPLAZA A LA TABLA \ref{tab:Sexo}, 

\begin{figure}[h]
\begin{center}
<<datprdd2, echo=FALSE, warning = FALSE, message = FALSE, fig.height = 5, fig.width = 6>>=

Predic_16_17 %>% filter(Centro_Grupo%in%factor(Cg)) %>% filter(coberturaT>47)  %>% dplyr::select(Abandono, Sexo) %>%
  mutate(Abandono = factor(Abandono) ) %>% group_by(Sexo, Abandono) %>% summarise(tot = n()) %>% ggplot() +
    geom_mosaic(aes(weight=tot, x=product(Abandono), fill = Sexo)) +
  scale_fill_brewer(palette = "Dark2") + labs(x = "Abandono", y = "", fill = "Género" )

@
\caption{Mosaicplot de Género vs Abandono. El ancho de cada categoría corresponde a la probabilidad asociada a abandono  mientras que la altura se corresponde con la probabilidad condicional de género dado abandono. En este caso estamos la informacioónde alumnos de la matrícula que abandonaron de 2016 a 2017 dentro de los que tienen cobertura homogenea y cuayo valor supere los 47 días por género}
\end{center}
\label{propabasub2}
\end{figure}

% 
% 
% \begin{figure}[h]
% \begin{center}
% <<datprdd, echo=FALSE, warning = FALSE, message = FALSE, fig.height = 5, fig.width = 6>>=
% Predic_16_17 %>% filter(Centro_Grupo%in%factor(Cg[,1])) %>% filter(coberturaT>47)  %>% dplyr::select(Abandono, Sexo) %>%
%   mutate(Abandono = factor(Abandono) ) %>% group_by(Sexo, Abandono) %>% summarise(tot = n()) %>% ggplot() +
%     geom_mosaic(aes(weight=tot, x=product(Sexo), fill = Abandono)) +
%   scale_fill_brewer(palette = "Dark2") + labs(x = "Género", y = "", fill = "Abandono" )
% 
% @
% \caption{Mosaicplot de Género vs Abandono. El ancho de cada categoría corresponde a la probabilidad asociada a cada género mientras que la altura se corresponde con la probabilidad condicional de Abandono. En este caso estamos la información de alumnos de la matrícula que abandonaron de 2016 a 2017 dentro de los que tienen cobertura homogenea y cuayo valor supere los 47 días por género}
% \end{center}
% \label{propabasub}
% \end{figure}

En el cuadro \ref{tab:Sexo} se relaciona el sexo del alumno con el abandono.
\begin{table}[htbp]
	\centering
	\begin{tabular}{|c|c|c|c|}
		\hline
	\rowcolor[rgb]{ .776,  .878,  .706}	& \multicolumn{1}{l|}{No abandona} & \multicolumn{1}{l|}{Abandona} & Población total \\
		\hline
		Femenino & 50,2\% & 43,2\% & 49,8\% \\
		\hline
		Masculino & 43,8\% & 56,6\% & 50,2\% \\
		\hline
		Total & 100,0\% & 100,0\% & 100\% \\
		\hline
	\end{tabular}%
	\caption{Abandono según Sexo}
	\label{tab:Sexo}%
\end{table}%


De los alumnos que abandonan, hay un porcentaje mayor de alumnos de sexo masculino. Mientras que de los alumnos que no abandonan hay un porcentaje mayor de alumnos del sexo femenino. Ambas diferencias no son muy pronunciadas.\\

 La variable \textbf{contexto sociocultural de los liceos} se creo en el marco de una investigación reciente realizada por Ceibal y el IESTA. En la misma se propuso una metodología que consiste en análisis de cluster, utilizada para inferir el contexto de los liceos a partir de la informaci?n de la procedencia de los alumnos. Esta información se basa en el contexto de la escuela de la que provienen los alumnos y la extra-edad de los mismos.
 
Los resultados de dicha investigación permitieron agrupar liceos con ``composiciones'' similares de procedencia. El resumen de dicha investigación se muestra en el cuadro \ref{tabla:clusters} 
	\begin{table}[H]
	\centering
	\begin{tabular}{|p{2cm}|p{12cm}|}
		\hline
\rowcolor[rgb]{ .776,  .878,  .706}		Grupo & Caracterizaci?n \\
		\hline \hline
		Cluster 1 & Se  compone de 45  liceos que concentran 26.675 alumnos. Donde la mayoría de los alumnos de 1ero provienen  del \textbf{Quintil 1} (más crítico) (78\%) y la mitad  presentan extraedad.\\
		\hline
		Cluster 2 & El cluster 2 está compuesto por 28 liceos y 10.739 alumnos.  La  matrícula de 1ero está compuesta fundamentalmente por alumnos del \textbf{Quintil 2} y en promedio el 44\% de los alumnos presentan extraedad. \\
		\hline
		Cluster 3 & Este cluster agrupa 73 liceos y 32.108 alumnos.   Si bien los alumnos provenientes del \textbf{Quintil 3} los que predominan es uno de los  cluster más heterogéneo. El promedio de extraedad es del 41\%. \\
		\hline	
		
		Cluster 4 & Compuesto por 28 liceos y 6.449 alumnos.  La matricula de 1ero mayormente proveniente del \textbf{Quintil 4} y con menores porcentajes en promedio de extraedad (30\%) en relación a los anteriores. \\
		\hline
		Cluster 5 & Conformado por 81 liceos y 45.040 alumnos.  Mayormente por alumnos del \textbf{Quintil 5} (menos crítico) y con una presencia de  extraedad en promedio del 32\% \\
		\hline
	\end{tabular}
	\caption{Caracterización de clusters.}
	\label{tabla:clusters}
\end{table} 

En el cuadro \ref{tab:AbandonoContexto} se relaciona el contexto sociocultural con el abandono del sistema educativo público.


ESTE PLOT REMPLAZA LA TABLA ref{tab:AbandonoContexto}
% \begin{figure}[h]
% \begin{center}
% <<datclus, echo=FALSE, warning = FALSE, message = FALSE, fig.height = 5, fig.width = 6>>=
% 
% Predic_16_17 %>% filter(Centro_Grupo%in%factor(Cg[,1])) %>% filter(coberturaT>47)  %>%dplyr::select(Abandono, cl) %>%
%   mutate(Abandono = factor(Abandono) ) %>% group_by(cl, Abandono) %>% summarise(tot = n()) %>%ggplot() + 
%     geom_mosaic(aes(weight=tot, x=product(Abandono), fill = cl)) +
%   scale_fill_brewer(palette = "Dark2") + labs(x = "Abandono", y = "", fill = "Cluster" )
% 
% @
% \caption{Mosaicplot de Abandono vs Cluster. El ancho de cada categoría corresponde a la probabilidad asociada a Abandono mientras que la altura se corresponde con la probabilidad condicional al Cluster. En este caso estamos la información de alumnos de la matrícula que abandonaron de 2016 a 2017 dentro de los que tienen cobertura homogenea y cuayo valor supere los 47 días por género}
% \end{center}
% \label{clab}
% \end{figure}

\begin{figure}[h]
\begin{center}
<<datclusja, echo=FALSE, warning = FALSE, message = FALSE, fig.height = 5, fig.width = 6>>=
Predic_16_17 %>% filter(Centro_Grupo%in%factor(Cg[,1])) %>% 
  filter(coberturaT>47)  %>%dplyr::select(Abandono, cl) %>%
  mutate(Abandono = factor(Abandono) ) %>% 
  group_by(cl, Abandono) %>% summarise(tot = n()) %>%
  group_by(Abandono) %>% mutate( total = sum(tot) ) %>%
  ungroup() %>% mutate( prop = tot/total ) %>%
  ggplot(aes(cl, prop, color=Abandono)) + geom_point() + geom_line()+
scale_color_brewer(palette = "Dark2") + labs(x = "Cluster", y = "Proporción", fill = "Cluster" )
@
\end{center}
\caption{Proporción de estudiantes en cada contexto según Abandono}
\label{clabw}
\end{figure}


\begin{table}[H]
	\centering
	\begin{tabular}{|c|c|c|c|}
		\hline
\rowcolor[rgb]{ .776,  .878,  .706}	& No Abandona & Abandona & Población total \\
		\hline
		Cluster 1 & 20.1\% &  25.6 \% & 20.4\% \\
		\hline
		Cluster 2 &  9.3\% &  11.5 \% & 9.5\% \\
		\hline
		Cluster 3 & 23.3\% &  28.4 \% & 23.6\% \\
		\hline
		Cluster 4 &  6.3\% &   2.6 \% & 6.1\% \\
		\hline
		Cluster 5 & 40.9\% &  31.9 \% & 40.4\% \\
		\hline
		Total & 100,0\% & 100,0\% &  100,0\% \\
		\hline
	\end{tabular}%
	\caption{Tabla perfil columna: Abandono según Contexto}
	\label{tab:AbandonoContexto}%
\end{table}%

En el cuadro \ref{tab:AbandonoContexto} se aprecia como alumnos que no abandonan tienen una composición similar a la de la población total, mientras que los alumnos que abandonan tienen mayor proporción de alumnos en los \textbf{clusters 1, 2 y 3} (más críticos) y menos proporción en los \textbf{clusters 4 y 5} (menos críticos).


En el cuadro \ref{tab:Abcol} se hace el mismo cuadro pero para el perfil fila.
\begin{table}[H]
	\centering
	
	\begin{tabular}{|c|c|c|c|}
		\hline
		\rowcolor[rgb]{ .776,  .878,  .706}	& No Abandona & Abandona & Total \\
		\hline
		Cluster 1 & 92.6\% &  7.4 \% & 100.0\% \\
		\hline
		Cluster 2 &  92.8\% &  7.2 \% & 100.0\% \\
		\hline
		Cluster 3 & 92.9\% &  7.1 \% & 100.0\% \\
		\hline
		Cluster 4 &  97.5\% &   2.5 \% & 100.0\% \\
		\hline
		Cluster 5 & 95.3\% &  4.7 \% & 100.0\% \\
		\hline
		Población total & 93.0\% & 7,0\% &  100,0\% \\
		\hline
	\end{tabular}%
	\caption{Tabla perfil fila: Abandono según Contexto}
	\label{tab:Abcol}%
\end{table}%
 
 
 \begin{figure}[h]
\begin{center}
<<datextra, echo=FALSE, warning = FALSE, message = FALSE, fig.height = 5, fig.width = 6>>=
Predic_16_17 %>% filter(Centro_Grupo%in%factor(Cg[,1])) %>% 
  filter(coberturaT>47)  %>%dplyr::select(Abandono, cl) %>%
  mutate(Abandono = factor(Abandono) ) %>% 
  group_by(cl, Abandono) %>% summarise(tot = n()) %>%
  group_by(cl) %>% mutate( total = sum(tot) ) %>% 
  ungroup() %>% mutate( prop = tot/total ) %>%
  ggplot(aes(cl, prop, color=Abandono)) + geom_point() + geom_line()+
scale_color_brewer(palette = "Dark2") + labs(x = "Cluster", y = "Proporción", fill = "Cluster" )
@
\end{center}
\caption{Proporción de estudiantes que Abandonan según Extra edad}
\label{extra}
\end{figure}
 \end{document}
 
Se aprecia que los alumnos que pertenecen a los cluster 1, 2 y 3 tienen un comportamiento similar al de la pobalción total, mientras que los que pertenecen al cluster 4 y 5 tienen tasas de abandono menores. 

Las tasas de abandono para los alumnos del cluster 5 es mayor que la de alumnos del cluster 4. Recordar que en este contexto, se toma en cuenta en abandono del sistema educativo público, por lo que puede haber casos de alumnos que vayan al sistema educativo privado.

\vspace{1cm}
En el gráfico \ref{fig:eefyab} se va a relacionar la extra-edad fuerte de los alumnos con el abandono del sistema educativo público.
%\begin{table}[htbp]
%	\centering
%	
%	\begin{tabular}{|c|c|c|c|}
%		\hline
%	\rowcolor[rgb]{ .776,  .878,  .706}	& No Abandona & Abandona & Poblaci?n total \\
%		\hline
%		Sin EE Fuerte & 89,1\% & 38,5\% & 86,1\%  \\
%		\hline
%		Con EE Fuerte & 10,9\% & 61,5\% & 13,9\%  \\
%		\hline
%		Total & 100,0\% & 100,0\% & 100,0\% \\
%		\hline
%	\end{tabular}%
%	\caption{Abandono seg?n Extra-edad Fuerte}
%	\label{tab:EEFuerte}%
%\end{table}%


\begin{figure}[H]
	\centering
	\includegraphics[width=0.5\linewidth]{EEFyAb}
	\caption{Extra edad fuerte y abandono}
	\label{fig:eefyab}
\end{figure}



\begin{figure}[h]
\begin{center}
<<datclus, echo=FALSE, warning = FALSE, message = FALSE, fig.height = 5, fig.width = 6>>=
#Calculo la extraedad Leve
Predic_16_17$EE_Leve <- 0
Predic_16_17[Predic_16_17$`Fecha nacimiento` < as.Date("2003-04-30"),]$EE_Leve<-1

#calculo la extraedad fuerte
Predic_16_17$EE_Fuerte<-0
Predic_16_17[Predic_16_17$`Fecha nacimiento` <as.Date("2002-04-30"),]$EE_Fuerte<-1


Predic_16_17 %>% filter(Centro_Grupo%in%factor(Cg)) %>% filter(coberturaT>47)%>%  dplyr::select(Abandono, EE_Fuerte) %>% 
  mutate(Abandono = factor(Abandono) ) %>% group_by( Abandono, EE_Fuerte) %>% summarise(tot = n()) %>%ggplot() +
    geom_mosaic(aes(weight=tot, x=product(Abandono), fill = EE_Fuerte)) +
  scale_fill_brewer(palette = "Dark2") + labs(x = "Abandono", y = "", fill = "Extra edad" )

@
\caption{Mosaicplot de Abandono vs Extra edad. El ancho de cada categoría corresponde a la probabilidad asociada a Abandono mientras que la altura se corresponde con la probabilidad condicional de Extra edad dado Abandono. En este caso estamos la información de alumnos de la matrícula que abandonaron de 2016 a 2017 dentro de los que tienen cobertura homogenea y cuayo valor supere los 47 días por género}
\end{center}
\label{clab}
\end{figure}
\end{document}
De los alumnos que no abandonan hay un gran porcentaje (89,1\%) que no tiene extra-edad fuerte, en cambio de los que abandonan hay un gran porcentaje (61,5\%) con extra-edad fuerte.


\newpage

En el gr?fico \ref{fig:eelyab} se va a relacionar la extra-edad leve de los alumnos con el abandono del sistema educativo p?blico.

%\begin{table}[htbp]
%	\centering
%	
%	\begin{tabular}{|c|c|c|c|}
%		\hline
%	\rowcolor[rgb]{ .776,  .878,  .706}	& No Abandona & Abandona & Poblaci?n total \\
%		\hline
%		Sin EE Leve & 68,3\% & 13,1\% & 65,0\% \\
%		\hline
%		Con EE Leve & 31,7\% & 86,9\% & 35,0\% \\
%		\hline
%		Total & 100,0\% & 100,0\% & 100,0\% \\
%		\hline
%	\end{tabular}%
%	\caption{Abandono seg?n Extra-edad Leve}
%	\label{tab:EELeve}%
%\end{table}%





\begin{figure}[H]
	\centering
	\includegraphics[width=0.5\linewidth]{EELyAb}
	\caption{Extra edad leve y abandono}
	\label{fig:eelyab}
\end{figure}


De los alumnos que no abandonan hay un gran porcentaje (68,3\%) que no tiene extra-edad leve, en cambio de los que abandonan hay un gran porcentaje (86,9\%) con extra-edad leve.




\newpage
En el gr?fico \ref{fig:inasistenciasrelativas} se muestra el gr?fico de densidad de las \textbf{inasistencias relativas} de los alumnos, recordar que la misma se calcula como el total de inasistencias del alumno sobre el total de veces que se le pas? la lista.

\begin{figure}[H]
	\centering
	\includegraphics[width=0.7\linewidth]{InasistenciasRelativas}
	\caption{Densidad de inasistencias relativas }
	\label{fig:inasistenciasrelativas}
\end{figure}

En este gr?fico de densidad se observa una gran masa de alumnos que tienen menos de 30\% de inasistencias relativas. Es decir, estos alumnos faltaron menos del 30\% del total de veces que le pasaron la lista.  

Menos del 10\% de los alumnos tienen m?s del 30\% de inasistencias relativas, para ver como es su relaci?n con el abandono, en la siguiente pagina se muestra un boxplot separando aquellos alumnos que abandonaron contra los que no lo hicieron.
\newpage
En el gr?fico \ref{fig:inasrel} se observan las inasistencias relativas para las dos poblaciones, de los alumnos que abandonan y de los que no. El \textit{boxplot} de la izquierda representa los alumnos que no abandonan el sistema educativo p?blico y el de la derecha los que si lo hacen.
\begin{figure}[H]
	\centering
	\includegraphics[width=0.7\linewidth]{Inas_rel}
	
	\caption{Inasistencias relativas seg?n abandono}
	\label{fig:inasrel}
\end{figure}
En el gr?fico se identifica claramente que los alumnos que abandonan tienen mayores porcentajes de inasistencias relativas. Es decir, la mitad de los alumnos que abandonan tienen entre un 22\% y un 43\% de inasistencias relativas. En cambio la mitad de los alumnos que no abandonan tienen entre un 1\% y un 10\% de inasistencias relativas


\newpage

	\section{Modelo log?stico de predicci?n}

Una vez realizado el an?lisis exploratorio de las variables y cada una de ellas con respecto a la variable dependiente se procede a realizar la experimentaci?n del modelo log?stico. 

\subsection{Metodolog?a}
Para establecer la relaci?n existente entre una variable dependiente Y, dicot?mica, y un conjunto de variables independientes $x=\left(x_{1},...,x_{k} \right)$ (que pueden ser tanto cualitativas como cuantitativas) se
puede ajustar una ecuaci?n de tal forma de que a trav?s de la estimaci?n de ciertos par?metros $\left(\beta_{0},\beta_{1},...,\beta_{k} \right)$ se prediga el comportamiento de Y \cite{L1}.

La variable respuesta $Y_{i}$ es una  \textit{variable aleatoria Bernulli}, con dos resultados posibles: \textit{exito o fracazo} codificados como $\left\lbrace 0,1\right\rbrace  $, los mismos tienen la siguiente distribuci?n: $P\left(Y_{i}=1\right)=\pi_{i}$, $P\left(Y_{i}=0\right)=1-\pi_{i}$, con esperanza	$ E\left(Y_{i}|X \right)=\pi_{i}$ .


%$$P\left(Y=1|X\right)=\pi=\frac{\exp^{\beta_{0}+\beta_{1}x_{1}+...+\beta_{k}x_{k} }}{1+\exp^{\beta_{0}+\beta_{1}x_{1}+...+\beta_{k}x_{k} }}$$

$$P\left(Y_{i}=1|X\right)=\pi_{i}=\frac{\exp^{\beta_{0}+\beta_{1}x_{1i}+...+\beta_{k}x_{ki} }}{1+\exp^{\beta_{0}+\beta_{1}x_{1i}+...+\beta_{k}x_{ki} }}$$


Dicho modelo puede ser linealizado mediante la transformaci?n $\log\left(\frac{\pi}{1-\pi} \right)$, la cu?l se denomina \textbf{transformaci?n logit}. El cociente $\frac{\pi}{1-\pi}$ se lo denomina \textbf{odds}, y es un cociente de probabilidades, la de ?xito sobre la de fracaso.\\

?Como se interpretan los \textbf{odds}?\\

Cuando se dice que los odds son 4 a 1 (odds=4) de que el alumno abandone el sistema educativo p?blico estamos diciendo que la probabilidad de que abandone es 0.8 ($4/5$).\\


%	En cambio cuando se dice que los odds de que un estudiante abandonde el sistema p?blico son de 1 a 3 (odds=1|3) estamos diciendo
%	que la probabilidad es 0.25.\\

Para estimar los par?metros $\beta$ del modelo se utiliza el m?todo de \textit{M?xima Verosimilitud}, buscando $\beta=\left(\beta_{1}...\beta_{p} \right) $ que maximice el logaritmo de la funci?n de verosimilitud, utilizando algoritmos de \textit{Newton-Raphson}.\\












\newpage
\subsection{Aplicaci?n del modelo}
En este estudio el objetivo es predecir si el alumno, que pertenece a primero de CES en el 2016, abandona el sistema educativo p?blico en 2017 o no. \textbf{Recordar que los mismos no necesariamente abandonan la educaci?n, puede ser que se anoten en el sistema privado. En este contexto cuando se menciona abandono se hace referencia al sistema educativo p?blico}.


Como se expuso en el cap?tulo \ref{cap3} la poblaci?n que se va a utilizar es aquellos alumnos que tengan una buena cobertura de pasaje de lista en linea. La misma est? compuesta por 28.232 alumnos, la cual se comporta de la siguiente manera:
\begin{itemize}
\item 26.566 alumnos (representados por el 94\% de la poblaci?n) que no abandonan el sistema educativo p?blico (0)

\item 1.666 alumnos (representados por el 6\% de la poblaci?n) que abandonan el sistema educativo p?blico (1)
\end{itemize}


\subsubsection{Variables a incluir en el modelo}

Luego de realizar el an?lisis exploratorio de las variables y la relaci?n que tiene cada una de ellas en el abandono, se exponen las mismas detallando su descripci?n y el recorrido que toman.


\begin{table}[H]
	\centering
	\begin{tabular}{|c|c|c|}
		\hline
		\rowcolor[rgb]{0.01, 0.28, 1.0}	Variable &  Descripci?n &   Recorrido \\
		\hline
		cl    & Cluster - contexto sociocultural del liceo en 1016 & 1,2,3,4,5\\
		\hline 	 		
		Sexo  & Sexo del alumno & F (femenino),M (masculino)  \\
		\hline 
		EE\_Fuerte & Si tiene m?s de un a?o m?s de la edad normativa & 1 (si tiene), 0(no tiene)\\
		\hline
		EE\_Leve & Si tiene un a?o m?s de la edad normativa & 1 (si tiene), 0(no tiene)\\
		\hline
		Abandona & Transici?n en la educaci?n p?blica 2016-2017 & 1(si abandona), 0(si no abandona) \\
		\hline
		inas\_rel & Cantidad de inasistencias sobre cobertura &  0,0 a 1,0. \\
		\hline
	\end{tabular}%
	\caption{Variables para incluir en el modelo}
	\label{variables}
\end{table}%

Luego se recodific? la variable cluster, el objetivo fue tener un recorrido mas acotado de la variable. Luego se va a evaluar como impacta en la \textit{performance} del modelo tener menos categor?as.\\


\begin{itemize}
\item Una forma de recodificaci?n fue separar en dos grupos. La variable se denomino \textbf{cl2} y se explica a continuaci?n:

\begin{itemize}
	\item Los cluster $\left\lbrace 1,2,3 \right\rbrace $ se agrupan en una categor?a que se llama \textbf{+crit}, en el que se identifican aquellos alumnos que provienen de escuelas de contexto sociocultural m?s cr?tico.
	
	\item Los cluster $\left\lbrace 4,5 \right\rbrace $ se agrupan en una categor?a que se llama \textbf{-crit}, en el que se identifican aquellos alumnos que provienen de escuelas de contexto sociocultural menos cr?tico.
\end{itemize}

\item La otra forma de recodificaci?n fue separar en tres grupos. La variable \textbf{cl3} se explica a continuaci?n.
\begin{itemize}
	\item Los cluster $\left\lbrace 1,2 \right\rbrace $ se agrupan en una categor?a que se llama \textbf{+crit}.
	
	\item El cluster $\left\lbrace 3 \right\rbrace $ queda solo en una categor?a que se llama \textbf{0crit}.
	
	
	\item Los cluster $\left\lbrace 4,5 \right\rbrace $ se agrupan en una categor?a que se llama \textbf{-crit}. 
\end{itemize}
\end{itemize}

\newpage
 

\subsubsection{Construcci?n del conjunto de entrenamiento}


Se va a dejar un 70\% del set de datos para entrenar el modelo y el 30\% restante para la validaci?n del modelo. La misma se hizo con un muestreo aleatorio simple sin reposici?n.


\begin{itemize}
\item La cantidad de alumnos que quedan en el conjunto de entrenamiento son 19.762, de los cuales:
\begin{itemize}
	\item 1.178  abandonan (el 6\%)
	\item 18.584 no abandonan (el 94\%)
\end{itemize}

\item La cantidad de alumnos que quedan en el conjunto de test son 8.470, de los cuales
\begin{itemize}
	\item 488 abandonan (el 6\%)
	\item 7.982 no abandonan (el 94\%)
\end{itemize}
\end{itemize}




\newpage
\subsection{Armado del los modelos}



\subsubsection{Modelo 1}
Se presenta en primer lugar la salida del resumen del modelo con todas las variables explicativas, obteniendo las estimaciones de los par?metros, las desviaciones est?ndar de los mismos, la distribuci?n \textit{z} y los p-valores.	

En el primer modelo se consideraron las siguientes variables X=inasistencias relativas, cluster, sexo y extra edad fuerte. 


\begin{table}[htbp]
	\centering
	
	\begin{tabular}{|c|c|c|c|c|c|}
		\hline
	\rowcolor[rgb]{0.01, 0.28, 1.0}	Coeficientes & Estimaci?n & Error std. & Valor z & $P(z>|z|)$ & Signif. \\
		\hline
		Intercepci?n & -4,14708 & 0,09302 & -44,58 & $<2,00E-16$ & *** \\
		\hline
		inas\_rel & 3,40618 & 0,16152 & 21,089 & $<2,00E-16$ & *** \\
		\hline
		cl2   & 0,11193 & 0,1207 & 0,927 & 0,3538 &  \\
		\hline
		cl3   & 0,48801 & 0,09372 & 5,207 & $<1,92E-07$ & *** \\
		\hline
		cl4   & -0,40947 & 0,21005 & -1,949 & 0,0512 & . \\
		\hline
		cl5   & 0,08448 & 0,09014 & 0,937 & 0,3486 &  \\
		\hline
		SexoM & 0,1228 & 0,06704 & 1,832 & 0,067 & . \\
		\hline
		EE\_Fuerte1 & 1,96389 & 0,07188 & 27,32 & $<2,00E-16$ & *** \\
		\hline
	\end{tabular}%
	\label{tab:Modelo1}%
	\caption{Resumen del \textbf{modelo 1} en el que se incluyen todas las variables menos extra edad leve. Se utiliza la variable cluster en su forma original}
\end{table}%


Las variables significativas con una confianza al 95\% seg?n el estad?stico de Wald en este modelo son:

\begin{itemize}
\item \textbf{inasistencias relativas}
\item \textbf{Cluster 3 al cu?l pertenece el liceo}
\item \textbf{extra-edad fuerte}  
\end{itemize} 

\subsubsection{Modelo 2}
Si en vez de utilizar la variable extra edad fuerte se utiliza la variable extra edad leve, el resumen del modelo es el siguiente:

\begin{table}[htbp]
	\centering
	\begin{tabular}{|c|c|c|c|c|c|}
		\hline
	\rowcolor[rgb]{0.01, 0.28, 1.0}	Coeficientes & Estimaci?n & Error std. & Valor z & $P(z>|z|)$ & Signif. \\
		\hline
		Intercepci?n & -4,80641 & 0,10954 & -43,878 & $<2,00E-16$ & *** \\
		\hline
		inas\_rel & 3,49542 & 0,1512 & 23,118 & $<2,00E-16$ & *** \\
		\hline
		cl2   & 0,10468 & 0,11708 & 0,894 & 0,371 &  \\
		\hline
		cl3   & 0,45889 & 0,09077 & 5,055 & $<4,30E-07$ & *** \\
		\hline
		cl4   & -0,33483 & 0,20687 & -1,619 & 0,106 &  \\
		\hline
		cl5   & 0,11131 & 0,08746 & 1,273 & 0,203 &  \\
		\hline
		SexoM & 0,06292 & 0,06579 & 0,956 & 0,339 &  \\
		\hline
		EE\_Leve1 & 2,09678 & 0,0914 & 22,94 & $<2,00E-16$ & *** \\
		\hline
	\end{tabular}%
	\label{tab:modelo2}%
		\caption{Resumen del \textbf{modelo 2} en el que se incluyen todas las variables menos extra edad fuerte. Se utiliza la variable cluster en su forma original}
\end{table}%
Las variables significativas son las mismas que en el \textbf{modelo 1}, solamente que se utiliza extra edad leve en vez de extra edad fuerte. 


\newpage
\subsubsection{Modelo 3}
En el siguiente modelo se utiliza la variable re-codificada para el cluster \textbf{cl2} en el que toma dos valores. Luego se presenta la salida del resumen del modelo con todas las variables explicativas, obteniendo las estimaciones de los par?metros, las desviaciones est?ndar de los mismos, la distribuci?n \textit{z} y los p-valores. 

En este \textbf{modelo 3} se consideraron las siguientes variables X=inasistencias relativas, \textbf{cl2} (en el que toma dos valores posibles), sexo y extra edad fuerte


% Table generated by Excel2LaTeX from sheet 'Hoja1'
\begin{table}[htbp]
	\centering
	\begin{tabular}{|c|c|c|c|c|c|}
		\hline
	\rowcolor[rgb]{0.01, 0.28, 1.0}	Coeficientes & Estimaci?n & Error std. & Valor z & $P(z>|z|)$ & Signif. \\
		\hline
		Intercepci?n & -4,12032 & 0,06271 & -65,703 & $< 2e-16$ & *** \\
		\hline
		inas\_rel & 3,46516 & 0,13441 & 25,781 & $< 2e-16$ & *** \\
		\hline
		cl2+crit & 0,17178 & 0,05854 & 2,934 & 0,00334 & ** \\
		\hline
		SexoM & 0,13534 & 0,05652 & 2,395 & 0,01664 & * \\
		\hline
		EE\_Fuerte1 & 1,94837 & 0,05998 & 32,484 & $< 2e-16$ & *** \\
		\hline
	\end{tabular}%
	\label{tab:model3}%
			\caption{Resumen del \textbf{modelo 3} en el que se incluyen todas las variables menos extra edad leve. Se utiliza la variable cluster en su forma recodificada como \textbf{cl2}}
\end{table}%


Se aprecia que todos los par?metros
estimados son significativos con una confianza mayor al 95 \%,
seg?n el estad?stico de Wald.\\

\subsubsection{Modelo 4}
En el siguiente modelo se prueba utilizar la variable re-codificada para el cluster \textbf{cl3} en el que toma tres valores. Luego se presenta la salida del resumen del modelo con todas las variables explicativas, obteniendo las estimaciones de los par?metros, las desviaciones est?ndar de los mismos, la distribuci?n \textit{z} y los p-valores. 

En este \textbf{modelo 4} se consideraron las siguientes variables X=inasistencias relativas, \textbf{cl3} (en el que toma dos valores posibles), sexo y extra edad fuerte

% Table generated by Excel2LaTeX from sheet 'Hoja1'
\begin{table}[htbp]
	\centering
	\begin{tabular}{|c|c|c|c|c|c|}
		\hline
	\rowcolor[rgb]{0.01, 0.28, 1.0}	Coeficientes & Estimaci?n & Error std. & Valor z & $P(z>|z|)$ & Signif. \\
		\hline
		Intercepci?n & -4,140107 & 0,063088 & -65,625 & $<2,00E-16$ & *** \\
		\hline
		inas\_rel & 3,529951 & 0,135458 & 26,059 & $<2,00E-16$ & *** \\
		\hline
		cl3+crit & 0,003955 & 0,067144 & 0,059 & 0,953 &  \\
		\hline
		cl30crit & 0,399365 & 0,070431 & 5,67  & $<1,43E-08$ & *** \\
		\hline
		SexoM & 0,131283 & 0,056606 & 2,319 & 0,0204 & * \\
		\hline
		EE\_Fuerte1 & 1,970298 & 0,060268 & 32,692 & $<2,00E-16$ & *** \\
		\hline
	\end{tabular}%
	\label{tab:model4}%
\caption{Resumen del \textbf{modelo 4} en el que se incluyen todas las variables menos extra edad leve. Se utiliza la variable cluster en su forma recodificada como \textbf{cl3}}
\end{table}%

Se aprecia que todos los par?metros
estimados son significativos con una confianza mayor al 95 \% (menos la variable \textbf{cl3}),
seg?n el estad?stico de Wald.\\

El modelo que se va a utilizar es el \textbf{modelo 3} en el que todas las variables son significativas, en la siguiente p?gina se va a realizar la validaci?n del mismo.

\newpage

\subsubsection{Validaci?n del modelo 3}

La significaci?n del modelo sirve para testear si el modelo es adecuado o no. Una prueba utilizada es la raz?n de verosimilitud del modelo. La misma se define como $\lambda=\dfrac{L_{R}}{L_{M}}$, donde $L_{M}$ es la verosimilitud del modelo completo $\frac{\exp^{\beta_{0}+\beta_{1}x_{1}+...+\beta_{p}x_{p} }}{1+\exp^{\beta_{0}+\beta_{1}x_{1}+...+\beta_{p}x_{p} }}$ y $L_{R}$ la del modelo reducido $\frac{\exp^{\beta_{0}+\beta_{1}x_{1}+...+\beta_{q}x_{q} }}{1+\exp^{\beta_{0}+\beta_{1}x_{1}+...+\beta_{q}x_{q} }}$, donde $p>q$.


$$H_{0})\beta_{1}=\beta_{2}=...=\beta_{p}=0$$

$$H_{1}) \text{alg?n} \; \beta_{k}\neq 0, \; k=1,2,...,p $$


$-2\log(\lambda)$ se distribuye $\chi^2_{(p+1-q)},\alpha$, siendo (p+1) y q la cantidad de par?metros incluidos en el modelo completo y el modelo reducido respectivamente.\\

\textbf{\textit{Test de raz?n de verosimilitud}}
$$ -2\log(\lambda)=-2\log(\dfrac{L_{R}}{L_{M}})=-2\left(  \log L_{R}-\log L_{M}\right)$$ 

La hip?tesis nula ser? rechazada para el nivel de significaci?n $\alpha$ cuando $-2\log(\lambda)>\chi^2_{(p+1-q)},\alpha$. Esto es equivalente a que el p valor del contraste sea menor que el nivel de significaci?n fijado \cite{L1}.\\
 

Para este \textbf{modelo 3} el \textit{Test de raz?n de verosimilitud} indica que el modelo es significativo, seg?n el valor de la tabla de una $\chi^2_{(p+1-q)},0.05$ el p-valor devuelto es muy peque?o. Esto se puede apreciar en la siguiente salida:

% Table generated by Excel2LaTeX from sheet 'Hoja1'
\begin{table}[htbp]
	\centering
	
	\begin{tabular}{|c|c|c|c|c|c|c|}
		\hline
	\rowcolor[rgb]{ .776,  .878,  .706}	& Df    & Deviance & Resid. Df & Resid. Dev & $Pr(>Chi)$ & Signif. \\
		\hline
		Modelo nulo &       &  & 28231 &    12661,4   &       &  \\
		\hline
		inas\_rel & 1     & 1828,18 & 28230 & 1,08E+04 & 2,20E-16 & *** \\
		\hline
		cl2   & 1     & 23,15 & 28229 & 10810 & 1,50E-06 & *** \\
		\hline
		Sexo  & 1     & 18,55 & 28228 & 10791,5 & 1,66E-05 & *** \\
		\hline
		EE\_Fuerte & 1     & 1022,13 & 28227 & 9769,4 & 2,20E-16 & *** \\
		\hline
	\end{tabular}%
	\label{tab:vero}%
	\caption{Test de raz?n de verosimilitud del modelo 3}
\end{table}%





Las variables que van a quedar en el modelo son las siguientes:

\begin{itemize}
	\item \textbf{inas\_rel}: inasistencias relativas
	\item \textbf{cl2}: el cluster en el que est? el liceo, con la variable recodificada que toma los valores \textbf{+crit} y \textbf{-crit}
	\item \textbf{Sexo} del alumno
	\item \textbf{EE\_Fuerte:} en el que toma el valor uno en el caso de que el alumno tenga m?s de un a?o de la edad normativa para la generaci?n que est? en 2016
\end{itemize}

\newpage
\subsection{Par?metros del modelo e interpretaci?n}

A continuaci?n se realizar? una descripci?n e interpretaci?n detallada de los par?metros del modelo elegido. 

Los par?metros del modelo son $\beta_{0}$, la ordenada en el origen, y $\left\lbrace \beta_{1},...,\beta_{p} \right\rbrace$, las pendientes. A veces se utilizan tambi?n como par?metros $exp(\beta_{0})$ y $exp(\beta_{i})$, que se denominan los odd ratios o ratios de probabilidades, e indican cuanto se modifican las probabilidades por unidad de cambio en las variables x \cite{L2}.

$$O_{i}=\frac{p_{i}}{1-p_{i}}=exp(\beta_{0})*\prod_{j=1}^{p} exp(\beta_{i})^{x_{j}} $$

Suponiendo que dos elementos ,i,k, con todos los valores de las variables iguales excepto la variable h y $x_{ih}=x_{ih}+1$. El cociente de los ratios de probabilidades (odds ratio) para estas dos observaciones es:

$$\frac{O_{i}}{O_{k}}=\exp^{\beta_{h}}     $$

Dicha igualdad indica cuanto se modifica el ratio de probabilidades cuando la variable $x_{h}$ aumenta una unidad.



\subsubsection{Interpretaci?n}


Para la interpretaci?n de los par?metros del modelo, se realizan los siguientes calculos:

\begin{enumerate}
	\item \textbf{T?rmino independiente}.\\
	El t?rmino independiente en el modelo de regresi?n log?stica es el siguiente:
	\begin{table}[H]
		\centering
		\begin{tabular}{|c|c|}
			\hline 
			\rowcolor[rgb]{ 1.0,  0.01,  .24}	\textbf{$\hat{\beta_{0}}$}  & $Exp(\hat{\beta_{0}})$  \\ 
			\hline 
			-4.12	& 0.016  \\ 
			\hline 
		\end{tabular} 
		\caption{T?rmino independiente}
	\end{table}
	
	\item \textbf{Inasistencias relativas.}\\
	
	Esta variable es la proporci?n de inasistencias del alumno en los d?as que le pasaron lista. El par?metro asignado a esta variable es:
	
	\begin{table}[H]
		\centering
		\begin{tabular}{|c|c|}
			\hline 
			\rowcolor[rgb]{ 1.0,  0.01,  .24}		\textbf{$\hat{\beta_{1}}$}  & $Exp(\hat{\beta_{1}})$  \\ 
			\hline 
			3.46	& 31.82  \\ 
			\hline 
		\end{tabular} 
		\caption{Estimaci?n del par?metro inasistencias relativas}
	\end{table}	
	
	Al aumentar las inasistencias relativas, dejando todas los dem?s valores constantes, el \textit{odd} ratio de Abandonar aumenta.
	Si aumenta en una unidad las inasistencias relativas, manteniendo las dem?s constantes la probabilidad de abandonar es 32 veces m?s grande que la de no abandonar.
	
	\item \textbf{Cluster 2.}\\
	El cluster en el que est? el liceo se divide en dos categor?as. El grupo \textbf{-crit} que es compuesto por liceos que se componen por alumnos que provienen de escuelas de los quintiles m?s favorables. El grupo \textbf{+crit} que es compuesto por liceos que se componen por alumnos que provienen de escuelas menos favorables, el valor del par?metro se imprime en el cuadro \ref{ECont}.
	
	\begin{table}[H]
		\centering
		\begin{tabular}{|c|c|}
			\hline 
			\rowcolor[rgb]{ 1.0,  0.01,  .24}		\textbf{$\hat{\beta_{2}}$}  & $Exp(\hat{\beta_{2}})$  \\ 
			\hline 
			0.17	& 1.19  \\ 
			\hline 
		\end{tabular} 
		\caption{Estimaci?n del par?metro cluster 2}
		\label{ECont}
	\end{table}
	Si el alumno pertenece al cluster \textbf{+crit} aumenta el odd ratio de abandonar el sistema con respecto al \textbf{-crit}, dejando el resto de las variables constantes.
	
	\item \textbf{Sexo}\\
	El peso asignado a la categoria masculino es:
	\begin{table}[H]
		\centering
		\begin{tabular}{|c|c|}
			\hline 
			\rowcolor[rgb]{ 1.0,  0.01,  .24}			\textbf{$\hat{\beta_{3}}$}  & $Exp(\hat{\beta_{3}})$  \\ 
			\hline 
			0.14	& 1.15  \\ 
			\hline 
		\end{tabular} 
		\caption{Estimaci?n del par?metro Sexo }
	\end{table}
	
	El sexo masculino aumenta el odd ratio de abandonar el sistema educativo p?blico con respecto al femenino, dejando el resto de los valores constantes.
	
	\item \textbf{Extra-edad Fuerte}.\\
	
	El peso asignado a la categoria que tiene extra-edad fuerte es:
	\begin{table}[H]
		\centering
		\begin{tabular}{|c|c|}
			\hline 
			\rowcolor[rgb]{ 1.0,  0.01,  .24}	\textbf{$\hat{\beta_{3}}$}  & $Exp(\hat{\beta_{3}})$  \\ 
			\hline 
			1.94	& 6.96  \\ 
			\hline 
		\end{tabular} 
		\caption{Estimaci?n del par?metro extra-edad fuerte}
	\end{table}
	
	Tener extra edad leve aumenta el odd ratio de abandonar el sistema educativo p?blico con respecto a no tener, dejando el resto de los valores constantes.
	
	
\end{enumerate}











\newpage
\subsection{Variable Predictora}

Predecir el valor de la variable de respuesta, en funci?n de ciertos valores de
las variables explicativas, implica determinar cual es el valor cr?tico a partir del cual las estimaciones del valor esperado implican un valor de 1 para la variable de respuesta. 


Valores grandes de $\pi_{i}$ implican $Y_{i} = 1$ mientras que valores chicos
de $\pi_{i}$ implican $Y_{i} = 0$. 

El problema a abordar es determinar cuando una estimaci?n es considerada un valor muy grande o muy chico. 

% Existen distintas aproximaciones a tener en cuenta para determinar el punto de corte, las mismas se van a 
% detallar en la subsecci?n siguiente.\\
	



\subsection{Evaluaci?n del punto de corte}
Para la evaluaci?n del punto de corte se van a evaluar distintas m?tricas. Las mismas son utilizadas para evaluar la exactitud y la capacidad de predicci?n del modelo. Es decir evaluar cu?ntos objetos se etiquetaron correctamente y cu?ntos no. Se definen las siguientes situaciones que pueden ocurrir en el proceso de clasificaci?n:


\begin{itemize}
	\item \textbf{Verdaderos positivos}. Un verdadero positivo es un alumno que abandon? y es clasificado correctamente por el modelo.
	\item \textbf{Falsos positivos}. Un falso positivo consiste en un alumno que no abandono, pero el modelo lo clasific? como que va a abandonar.
	\item \textbf{Verdaderos negativos}.  Un verdadero negativo es un alumno que no abandona y el modelo lo clasifica correctamente.
	\item \textbf{Falsos negativos}.Un falso negativo es un alumno que abandona pero el modelo lo clasifica como que no.
\end{itemize}

Utilizando las definiciones mencionadas anteriormente; el clasificador puede ser evaluado con las siguiente m?tricas:


 $$Ratio \; de \; Verdaderos \; Positivos= \frac{ Positivos \; clasificados \; correctamente}{Total \; de \; positivos} $$ 


 $$Ratio \; de \; Falsos \; Positivos= \frac{ Positivos \; clasificados \; incorrectamente}{Total \; de \; negativos} $$ 










\newpage
\subsection{Desempe?o del clasificador}

Una forma de evaluar la calidad de ajuste de un modelo es utilizando la
curva ROC (Receiver Operating Characteristic), que capta las caracter?sticas
del funcionamiento del modelo a trav?s de la variaci?n de su comportamiento.


En la curva ROC se grafica el ratio de verdaderos positivos en el eje de las abscisas y el ratio de falsos positivos en el eje de las ordenadas, seg?n diferentes puntos de corte.


En la figura \ref{fig:roc} se hace una curva ROC para evaluar el mejor punto de corte utilizando el conjunto de datos de test:
\begin{figure}[H]
	\centering
	\includegraphics[width=0.5\linewidth]{ROC}
	\caption{curva ROC}
	\label{fig:roc}
\end{figure}


En el siguiente cuadro se imprimen los valores del ratio de verdaderos positivos (TP) y ratio de falsos positivos (FP) seg?n distintos puntos de corte.


\begin{table}[H]
	\centering

	\begin{tabular}{|c|c|c|}
		\hline
		Punto de corte & Ratio de TP & Ratio de FP \\
		\hline
		0,77  & 0,00  & 0,00 \\
		\hline
		.     & .     & . \\
		\hline
		0,11  & 0,67  & 0,12 \\
		\hline
		0,10  & 0,67  & 0,12 \\
		\hline
		0,09  & 0,69  & 0,12 \\
		\hline
		0,08  & 0,70  & 0,12 \\
		\hline
		0,07  & 0,71  & 0,13 \\
		\hline
		0,06  & 0,74  & 0,14 \\
		\hline
		0,05  & 0,77  & 0,15 \\
		\hline
\rowcolor[rgb]{0.87, 0.36, 0.51}		0,04  & 0,81  & 0,18 \\
		\hline
		0,03  & 0,89  & 0,32 \\
		\hline
		0,02  & 1,00  & 0,93 \\
		\hline
	\end{tabular}%
	\label{tab:addlabel}%
		\caption{Punto de corte ?ptimo ultimos 10 valores}
\end{table}%




\newpage
\section{Conclusiones}
El mejor desempe?o se tiene con un punto de corte igual a 0,04. El desempe?o del clasificador es el siguiente:


% Table generated by Excel2LaTeX from sheet 'Hoja1'
\begin{table}[H]
	\centering

	\begin{tabular}{|c|c|c|c|}
		\hline
	\rowcolor[rgb]{0.87, 0.36, 0.51}	& Realidad no abanona & Realidad abandona & Total \\
		\hline\subsection{Poblaci?n de estudio}
La poblaci?n que se va a analizar son los \textbf{estudiantes de primero de CES que cursan primero en el a?o 2016}. Dicha poblaci?n se compone de una matr?cula de 40.293 alumnos, que pertenecen a 254 centros educativos de educaci?n media p?blica.\\




\begin{table}[H]
	\centering
	
	\begin{tabular}{||c||c|c|}
		
		
		\hline 
		\rule[-1ex]{0pt}{2.5ex} \cellcolor[rgb]{ .663,  .816,  .557} Matr?cula 2016 & \cellcolor[rgb]{ .663,  .816,  .557} ANEP* & \cellcolor[rgb]{ .663,  .816,  .557} CEIBAL (UE)** \\ 
		\hline 
		\rule[-1ex]{0pt}{2.5ex} 1? CES-Ciclo b?sico &  & 40.293 \\ 
		\hline 

	\end{tabular} 
	\caption{Cantidad de Matriculados.}
	\label{Matricula}
\end{table}



\scriptsize{\textit{* Fuente: Monitor Liceal CES (Incluye Ref. 2006; Plan 1996 Extraedad; Plan Ciclo B?sico 2009; Ad. Plan 09 semi-presencial; Plan 2012 CB Extraedad-Propuesta 2016 )Ref 2006 + Ref 2006 CB Rural )= 107.392 ; (0tros Planes) = 15.374\\
**Fuente: CRM}}

\vspace{2cm}
\normalsize



\newpage

\section{Analisis descriptivo}

El primer an?lisis exploratorio que se va a realizar tiene como objetivo describir las variables disponibles. Encontrar la relaci?n entre las mismas y evaluar cuales son las que tienen mayor impacto en el abandono.


\subsection{Descripci?n del set de datos}
Se va a utilizar la base de datos \textbf{Predic\_16\_17}. La misma re?ne informaci?n que proviene de diferentes fuentes, las cuales se detallan a continuaci?n: 

\begin{itemize}
\item \textbf{\underline{Marco Uruguay Estudia 2016}}, de ahora en m?s \textbf{Marco UE 2016}. Este set de datos tiene informaci?n correspondiente a cada uno de los alumnos matriculados en CES en el a?o 2016. La misma se conforma por el centro educativo al cu?l esta concurriendo el alumno, departamento al que pertenece dicho centro, grado del alumno y grupo. 


\item \textbf{\underline{Marco Uruguay Estudia 2017}}, de ahora en m?s \textbf{Marco UE 2017}. Este set de datos tiene la informaci?n de la matr?cula de CES del a?o 2017. Dicha informaci?n es de suma importancia para investigar la transici?n educativa de los alumnos entre 2016 y 2017. Uno de los aspectos claves fue detectar cuantos alumnos matriculados en el \textbf{Marco UE 2016} se encuentran registrados en el \textbf{Marco UE 2017}.

\item \textbf{\underline{Pasaje de lista en linea proporcionado por Uruguay Estudia}}, de ahora en m?s \textbf{Marcas UE 2016}. Este set de datos tiene la informaci?n del pasaje de lista en linea por parte de Uruguay Estudia. Para este an?lisis se van a tomar en cuenta 57 d?as, desde el 28 de marzo de 2016 hasta el 24 de junio de 2016 (la semana antes de las vacaciones de Julio).


\item \textbf{\underline{An?lisis de la trayectoria del alumno desde 2013 hasta 2016}} proporcionada por CRM, de ahora en m?s \textbf{Trayectorias}. Dicho set de datos tiene el seguimiento acad?mico de los estudiantes, es decir los grados cursados desde 2013 hasta 2016. Tambi?n la fecha de nacimiento de cada uno de los alumnos (dicha informaci?n es de relevancia para calcular si el alumno tienen extra-edad).


 


\item \textbf{\underline{Contexto sociocultural del liceo}}, de ahora en m?s \textbf{Contextos}. Esta informaci?n fue creada en un trabajo anterior (por parte de Ceibal y el IESTA) en el cual se experiment? una metodolog?a para estimar el contexto de los liceos.

\end{itemize}   





En el cuadro \ref{tab:VAR} de la secci?n \ref{VD} se va a detallar las variables utilizadas de cada conjunto de datos mencionados. Las mismas se re?nen en el set de datos \textbf{Predic\_16\_17.RData}.




\subsubsection{Variables disponibles} \label{VD}
\begin{table}[H]
	\centering
	
	\begin{tabular}{|c|c|c|}
		\hline
	\rowcolor[rgb]{ .776,  .878,  .706}	Variable &  Descripci?n &   Fuente \\
		\hline
		documento & C?dula de Identidad del alumno & \textbf{Marco UE 2016} \\
		\hline
		nro\_doc\_centro\_educ & Liceo que concurre el alumno en 2016 & \textbf{Marco UE 2016} \\
		\hline
		nombre\_departamento & Nombre del Departamento del centro educativo & \textbf{Marco UE 2016} \\
		\hline
		grupo\_desc & Grupo del alumno en 2016 & \textbf{Marco UE 2016} \\
		\hline
		coberturaT & Cobertura en el primer semestre de 2016  & \textbf{Marcas UE 2016} \\
		\hline
		Centro\_Grupo & Liceo y grupo del alumno en 2016 & \textbf{Marco UE 2016} \\
		\hline
		cl    & Cluster - contexto sociocultural del liceo en 1016 & \textbf{Contextos} \\
		\hline
		Grado\_2016\_UE & Grado del alumno en el 2016 seg?n UE & \textbf{Marco UE 2016} \\
		\hline
		Grado2013 & Grado del alumno en 2013 seg?n CRM & \textbf{Trayectorias} \\
		\hline
		Grado2014 & Grado del alumno en 2014 seg?n CRM & \textbf{Trayectorias} \\
		\hline
		Grado2015 & Grado del alumno en 2015 seg?n CRM & \textbf{Trayectorias} \\
		\hline
		Grado 2016 & Grado del alumno en 2016 seg?n CRM & \textbf{Trayectorias} \\
		\hline
		Sexo  & Sexo del alumno & \textbf{Trayectorias}  \\
		\hline
		Fecha.nacimiento & Fecha de nacimiento del alumno & \textbf{Trayectorias} \\
		\hline
		Grupo\_UE\_2017 & Grupo del alumno en 2017 & \textbf{Marco UE 2017} \\
		\hline
		inasistencias & cantidad de inasistencias en el primer semestre de 2016 & \textbf{Marcas UE 2016} \\
		\hline
		asistencias & cantidad de asistencias en el primer semestre de 2016 & \textbf{Marcas UE 2016} \\
		\hline
	\end{tabular}%
	\caption{Variables de 
	\label{tab:VAR}%
	\textbf{Predic\_16\_17.RData}}
\end{table}%





A partir de dichas variables disponibles, se construyeron otras, las mismas se detallan a continuaci?n:

\begin{itemize}
\item \textbf{Extra-edad Leve}: Se considera que el alumno tiene extra-edad leve cu?ndo nace antes del 30 de abril de 2003 . Es decir un a?o m?s de la edad normativa para dicha generaci?n.

\item \textbf{Extra-edad Fuerte}: Se considera que el alumno tiene extra-edad fuerte cu?ndo nace antes del 30 de abril de 2002. Es decir dos a?os m?s de la edad normativa para dicha generaci?n.

\item \textbf{Inasistencias relativas}: Se calculan como el total de inasistencias del alumno sobre el total de veces que se le paso lista (en los 57 d?as considerados). Por ejemplo si a un alumno le pasaron lista 40 veces de las cuales 20 no asisiti? al centro, su inasistencia relativa es 20/40=0.5 (asisti? a la mitad de los d?as que se le paso lista).


\item \textbf{Abandono:} Esta variable hace referencia a aquellos alumnos matriculados en el \textbf{Marco UE 2016} que en el 2017 no est?n anotados en el sistema de educaci?n p?blica en el \textbf{Marco UE 2017}.\textbf{Es necesario aclarar que los mismos no necesariamente abandonaron la educaci?n, puede ser que est?n anotados en el sistema privado. En este contexto cuando se menciona abandono se hace referencia a el sistema educativo p?blico}

\end{itemize}





\newpage
\subsection{Matr?cula 2016 seg?n departamento}

La matricula de primero de CES,   conformada por 40.233 estudiantes, que pertenecen a diferentes departamentos del Uruguay. Dicha composici?n se puede observar en el cuadro \ref{tab:Dep}.
\begin{table}[H]
	\centering
	\begin{tabular}{|c|c|c|c|}
		\hline
	\rowcolor[rgb]{ .776,  .878,  .706}	Departamento & Cantidad de alumnos & Departamento & Cantidad de alumnos \\
		\hline
		Artigas & 1.139  & Paysandu & 1.514 \\
		\hline
		Canelones & 7.143  & Rio Negro & 745 \\
		\hline
		Cerro Largo & 1.098  & Rivera & 1.889 \\
		\hline
		Colonia & 1.487  & Rocha & 1.070 \\
		\hline
		Durazno & 654   & Salto & 1.759 \\
		\hline
		Flores & 367   & San Jos? & 1.406 \\
		\hline
		Florida & 885   & Soriano & 1.204 \\
		\hline
		Lavalleja & 834   & Tacuarembo & 1.545 \\
		\hline
		Maldonado & 2.123  & Treinta y Tres & 711 \\
		\hline
		Montevideo & 12.660 & Total & 40.233 \\
		\hline
	\end{tabular}%
	\caption{Composici?n de la matricula seg?n departamento}
	\label{tab:Dep}%
\end{table}%





\subsection{Trnasici?n educativa entre 2016-2017}
En esta secci?n se va a estudiar la transici?n educativa de los 40.233 alumnos matr?culados en primero de CES en 2016 \footnote{60 alumnos no se tuvieron en cuenta ya que si estaban en el set de datos \textbf{Marco UE 2016} pero no se encontraron en el set de datos \textbf{Trayectorias}}, de forma tal de observar en que situaci?n se encuentran en 2017. En el cuadro \ref{tab:Abandono} se muestra la cantidad de alumnos que estaban cursando primero de CES en 2016 y en 2017 no se anotaron en el sistema de educaci?n p?blica.
\begin{table}[H]
	\centering
	
	\begin{tabular}{|c|c|c|}
		\hline
\rowcolor[rgb]{ .776,  .878,  .706}		No Abandona & Abandona & Total \\
		\hline
		37.535 & 2.698 & 40.233 \\
		\hline
		93,0\% & 7,0\% & 100,0\% \\
		\hline
	\end{tabular}%
	
	\caption{Cantidad de alumnos de la matr?cula que abandonaron de 2016 a 2017}
	\label{tab:Abandono}%
\end{table}%
El 93\% de los alumnos siguen anotados en el sistema de educaci?n p?blica en el 2017, mientras que del 7\% restante no se encontraron registros de inscripci?n en dicho sistema. \textbf{Recordar que los mismos no necesariamente abandonaron la educaci?n, puede ser que est?n anotados en el sistema privado}.



El 93\% de la matr?cula que sigui? en el sistema educativo p?blico en el 2017 se anotaron en diferentes grados, en el cuadro \ref{Destino} se detalla cu?l fue el destino de esos estudiantes. 

\begin{table}[H]
	\centering
	\begin{tabular}{|c|c|c|c|c|}
		\hline
\rowcolor[rgb]{ .776,  .878,  .706}		1?    & 2?    & CBT   & FPB   & Total \\
		\hline
		7.450 & 28.786 & 348   & 951   & 37.535 \\
		\hline
		19,8\% & 76,7\% & 0,9\% & 2,5\% & 100\% \\
		\hline
	\end{tabular}%
	\label{tab:addlabel}%
	\caption{Destino de alumnos que siguen matriculados desde 2016 a 2017}
	\label{Destino}
\end{table}%

El 76,7\% de los alumnos que siguen matriculados pasan a segundo grado de CES, mientras que el 19,8\% cursan nuevamente primero. Hay una peque?a proporci?n de alumnos que se anotan en CBT (Ciclo B?sico Tecnol?gico) y otra peque?a porci?n en FPB (Formaci?n Profesional B?sica).\\

\vspace{2cm}
\subsection{An?lisis de la cobertura del pasaje de lista en l?nea}
El primer an?lisis que se va a realizar es evaluar que todos los grupos tengan una cobertura homog?nea, es decir que a los alumnos del mismo grupo le pasen la lista la misma cantidad de d?as.

Para esto se creo una variable que se llama \textbf{Predominio}. La misma es el porcentaje m?s grande de alumnos (del mismo grupo) que tienen la misma cobertura. Es decir si a un grupo X al 90\% de los alumnos le pasan 20 veces la lista, al 5\% le pasan 15 veces y al 5\% restante le pasan solo una vez, la variable \textbf{Predominio} tiene el valor 90\% (el porcentaje mas grande de alumnos con la misma cobertura), en el gr?fico \ref{fig:pred} se ilustra el comportamiento de dicha variable para cada uno de los grupos en un histograma.

\begin{figure}[H]
	\centering
	\includegraphics[width=0.7\linewidth]{Cobertura}
	\caption{Predominio de la cobertura}
	\label{fig:pred}
\end{figure}

Lo esperable es que todos los alumnos del grupo tengan la misma cobertura es decir que el predominio sea 100\%. Hay 560 grupos que cumplen con el valor esperado los mismos est?n representados en la barra m?s contra la derecha en el histograma.

Si bien no todos los grupos est?n en la situaci?n ideal, en el histograma queda representado que en la mayor?a de los grupos, m?s del 80\% de sus alumnos tienen la misma cobertura.



Hay 1.437 grupos (de un total de 1.513, es decir un 95\%) en el que el 80\% o m?s de los alumnos tiene la misma cobertura. Por lo que se concluye que la cobertura a nivel de grupos es ``aceptable''. En lo que sigue del an?lisis se va tomar en cuenta  dicho 95\% de los grupos que tienen una cobertura inra-grupos homog?nea, dichos grupos tienen 37.849 alumnos. 





\vspace{2cm}
Se va a analizar como es la \textbf{cobertura} del pasaje de lista en linea, la misma no es igual para todos los centros, es decir hay algunos que tienen mayor cobertura que otros. 


En el gr?fico \ref{fig:cobertura} se realiza un boxplot de la variable cobertura en los 57 d?as que se est? evaluando. La misma se realiz? para el 95\% de los grupos que tienen una cobertura intra-grupos homog?nea.





\begin{figure} [H]
	\centering
	\includegraphics[width=0.5\linewidth]{cobertura2}
	\caption{Cobertura del pasaje de lista en linea}
	\label{fig:cobertura}
\end{figure}



Los nivele de cobertura, para dicha poblaci?n, son buenos. Como se representa en el boxplot de la figura \ref{fig:cobertura}, al 75\% de los alumnos pertenecientes a dicha poblaci?n se le pas? 47 d?as o m?s la lista (de los 57 d?as en los que se est? analizando). Por lo que se entiende que es una buena cobertura para realizar el an?lisis.\\ 

Para realizar el modelo se van a tomar los grupos que tienen una cobertura homog?nea (es decir aquellos que m?s del 80\% de los alumnos del grupo tienen la misma cobertura) y ademas que dicho valor supere los 47 d?as. En esta situaci?n hay 28.232 alumnos (que pertenecen a 1.095 grupos diferentes). En lo que resta de este an?lisis se va a trabajar con esa poblaci?n de estudio.






\newpage
\section{Analisis exploratorio de las covariables}\label{cap3}

\subsubsection{Selecci?n de la poblaci?n de estudio}
\textbf{Se utilizar? una porci?n de la totalidad de los estudiantes matriculados en primero de CES en 2016}. Un factor importante a la hora de evaluar el abandono, el cu?l se observ? en el an?lisis exploratorio, son las inasistencias del alumno. Por lo que se entiende que la cobertura del pasaje de lista en linea (de los estudiantes analizados) tiene que ser buena.

Por esta raz?n el criterio para la elecci?n de los estudiantes, con los que se va a inferir el modelo predictivo, es seleccionar aquellos que tengan una buena cobertura de pasaje de lista en linea.\\



Como se expuso en el an?lisis descriptivo de un total de 1.513 grupos, hay 1.437 (el 95\%) que tienen una cobertura homog?nea (es decir, todos los alumnos del grupo tienen la misma cobertura). De dichos grupos 1.095 tienen una cobertura mayor a 47 d?as. Los mismos est?n compuestos por 28.232 alumnos y son los que se van a considerar en el an?lisis predictivo.\\ 

\begin{figure}[H]
	\centering
	\begin{tikzpicture}[thick]
	\draw (4,-3) rectangle (-2,2) node[below right] {1.513 grupos};
	
	\draw (1,-0.5) [fill=cyan]  circle (1.8) node[above,shift={(0.4,0.7)}] {};
	
	
	\draw (1,-0.5) circle (2.3) node[above,shift={(0,1.8)}] {};
	
	
	\node at (1,1.4) {1.437 grupos};
	\node at (1.1,-.4) {1.095 grupos};
	%\node at (1.1,-.8) {28.566 alumnos};
	
	\end{tikzpicture}
	\caption{Selecci?n de grupos para incluir en el modelo predictivo}
	%\label{fig:Selec}
\end{figure}


\newpage
Primero se va a evaluar como es la transici?n entre 2016 y 2017 para dicha poblaci?n, es decir cuantos alumnos abandonan y cuantos siguen matriculados en 2017.\\

\begin{table}[H]
	\centering
	
	\begin{tabular}{|c|c|c|}
		\hline
		\rowcolor[rgb]{ .776,  .878,  .706}		No Abandona & Abandona & Total \\
		\hline
		26.566 & 1.666 & 28.232 \\
		\hline
		94,0\% & 6,0\% & 100,0\% \\
		\hline
	\end{tabular}%
	
	\caption{Cantidad de alumnos de la matr?cula que abandonaron de 2016 a 2017}
	\label{tab:Abandono2}%
\end{table}%

La proporci?n de alumnos que abandonan y los que no, tiene un comportamiento muy similar al de la matr?cula total que se compone de la siguiente manera:

\begin{table}[H]
	\centering
	
	\begin{tabular}{|c|c|c|}
		\hline
		\rowcolor[rgb]{ .776,  .878,  .706}		No Abandona & Abandona & Total \\
		\hline
		37.535 & 2.698 & 40.233 \\
		\hline
		93,0\% & 7,0\% & 100,0\% \\
		\hline
	\end{tabular}%
	
	\caption{Cantidad de alumnos de la matr?cula que abandonaron de 2016 a 2017}
	\label{tab:Aband2}%
\end{table}%





En el cuadro \ref{tab:Sexo} se relaciona el sexo del alumno con el abandono.
\begin{table}[htbp]
	\centering
	
	\begin{tabular}{|c|c|c|c|}
		\hline
	\rowcolor[rgb]{ .776,  .878,  .706}	& \multicolumn{1}{l|}{No abandona} & \multicolumn{1}{l|}{Abandona} & Poblaci?n total \\
		\hline
		Femenino & 50,2\% & 43,2\% & 49,8\% \\
		\hline
		Masculino & 43,8\% & 56,6\% & 50,2\% \\
		\hline
		Total & 100,0\% & 100,0\% & 100\% \\
		\hline
	\end{tabular}%
	\caption{Abandono seg?n Sexo}
	\label{tab:Sexo}%
\end{table}%



De los alumnos que abandonan, hay un porcentaje mayor de alumnos de sexo masculino. Mientras que de los alumnos que no abandonan hay un porcentaje mayor de alumnos del sexo femenino. Ambas diferencias no son muy pronunciadas.\\

\newpage
 La variable \textbf{contexto sociocultural de los liceos} se creo en el marco de una investigaci?n reciente realizada por Ceibal y el IESTA. En la misma se propuso una metodolog?a que consiste en an?lisis de cluster, utilizada para inferir el contexto de los liceos a partir de la informaci?n de la procedencia de los alumnos. Esta informaci?n se basa en el contexto de la escuela de la que provienen los alumnos y la extra-edad de los mismos.

Los resultados de dicha investigaci?n permitieron agrupar liceos con ``composiciones'' similares de procedencia. El resumen de dicha investigaci?n se muestra en el cuadro \ref{tabla:clusters} 
	\begin{table}[H]
	\centering
	\begin{tabular}{|p{2cm}|p{12cm}|}
		\hline
\rowcolor[rgb]{ .776,  .878,  .706}		Grupo & Caracterizaci?n \\
		\hline \hline
		Cl?ster 1 & Se  compone de 45  liceos que concentran 26.675 alumnos. Donde la mayor?a de los alumnos de 1? provienen  del \textbf{Quintil 1} (m?s critico) (78\%) y la mitad  presentan extraedad.\\
		\hline
		Cl?ster 2 & El cl?ster 2 est? compuesto por 28 liceos y 10.739 alumnos.  La  matr?cula de 1? est? compuesta fundamentalmente por alumnos del \textbf{Quintil 2} y en promedio el 44\% de los alumnos presentan extraedad. \\
		\hline
		Cl?ster 3 & Este cl?ster agrupa 73 liceos y 32.108 alumnos.   Si bien los alumnos provenientes del \textbf{Quintil 3} los que predominan es uno de los  cl?ster m?s heterog?neo. El promedio de extraedad es del 41\%. \\
		\hline	
		
		Cl?ster 4 & Compuesto por 28 liceos y 6.449 alumnos.  La matricula de 1? mayormente proveniente del \textbf{Quintil 4} y con menores porcentajes en promedio de extraedad (30\%) en relaci?n a los anteriores. \\
		\hline
		Cl?ster 5 & Conformado por 81 liceos y 45.040 alumnos.  Mayormente por alumnos del \textbf{Quintil 5} (menos cr?tico) y con una presencia de  extraedad en promedio del 32\% \\
		\hline
	\end{tabular}
	\caption{Caracterizaci?n de cl?sters.}
	\label{tabla:clusters}
\end{table} 

En el cuadro \ref{tab:AbandonoContexto} se relaciona el contexto sociocultural con el abandono del sistema educativo p?blico.


\begin{table}[H]
	\centering

	\begin{tabular}{|c|c|c|c|}
		\hline
\rowcolor[rgb]{ .776,  .878,  .706}	& No Abandona & Abandona & Poblaci?n total \\
		\hline
		Cluster 1 & 20.1\% &  25.6 \% & 20.4\% \\
		\hline
		Cluster 2 &  9.3\% &  11.5 \% & 9.5\% \\
		\hline
		Cluster 3 & 23.3\% &  28.4 \% & 23.6\% \\
		\hline
		Cluster 4 &  6.3\% &   2.6 \% & 6.1\% \\
		\hline
		Cluster 5 & 40.9\% &  31.9 \% & 40.4\% \\
		\hline
		Total & 100,0\% & 100,0\% &  100,0\% \\
		\hline
	\end{tabular}%
	\caption{Tabla perfil columna: Abandono seg?n Contexto}
	\label{tab:AbandonoContexto}%
\end{table}%




En el cuadro \ref{tab:AbandonoContexto} se aprecia como alumnos que no abandonan tienen una composici?n similar a la de la poblaci?n total, mientras que los alumnos que abandonan tienen mayor proporci?n de alumnos en los \textbf{clusters 1, 2 y 3} (m?s cr?ticos) y menos proporci?n en los \textbf{clusters 4 y 5} (menos cr?ticos).

\newpage
En el cuadro \ref{tab:Abcol} se hace el mismo cuadro pero para el perfil fila.
\begin{table}[H]
	\centering
	
	\begin{tabular}{|c|c|c|c|}
		\hline
		\rowcolor[rgb]{ .776,  .878,  .706}	& No Abandona & Abandona & Total \\
		\hline
		Cluster 1 & 92.6\% &  7.4 \% & 100.0\% \\
		\hline
		Cluster 2 &  92.8\% &  7.2 \% & 100.0\% \\
		\hline
		Cluster 3 & 92.9\% &  7.1 \% & 100.0\% \\
		\hline
		Cluster 4 &  97.5\% &   2.5 \% & 100.0\% \\
		\hline
		Cluster 5 & 95.3\% &  4.7 \% & 100.0\% \\
		\hline
		Poblaci?n total & 93.0\% & 7,0\% &  100,0\% \\
		\hline
	\end{tabular}%
	\caption{Tabla perfil fila: Abandono seg?n Contexto}
	\label{tab:Abcol}%
\end{table}%
 
Se aprecia que los alumnos que pertenecen a los cluster 1, 2 y 3 tienen un comportamiento similar al de la pobalci?n total, mientras que los que pertenecen al cluster 4 y 5 tienen tasas de abandono menores. 

Las tasas de abandono para los alumnos del cluster 5 es mayor que la de alumnos del cluster 4. Recordar que en este contexto, se toma en cuenta en abandono del sistema educativo p?blico, por lo que puede haber casos de alumnos que vayan al sistema educativo privado.




\vspace{1cm}
En el gr?fico \ref{fig:eefyab} se va a relacionar la extra-edad fuerte de los alumnos con el abandono del sistema educativo p?blico.
%\begin{table}[htbp]
%	\centering
%	
%	\begin{tabular}{|c|c|c|c|}
%		\hline
%	\rowcolor[rgb]{ .776,  .878,  .706}	& No Abandona & Abandona & Poblaci?n total \\
%		\hline
%		Sin EE Fuerte & 89,1\% & 38,5\% & 86,1\%  \\
%		\hline
%		Con EE Fuerte & 10,9\% & 61,5\% & 13,9\%  \\
%		\hline
%		Total & 100,0\% & 100,0\% & 100,0\% \\
%		\hline
%	\end{tabular}%
%	\caption{Abandono seg?n Extra-edad Fuerte}
%	\label{tab:EEFuerte}%
%\end{table}%


\begin{figure}[H]
	\centering
	\includegraphics[width=0.5\linewidth]{EEFyAb}
	\caption{Extra edad fuerte y abandono}
	\label{fig:eefyab}
\end{figure}





De los alumnos que no abandonan hay un gran porcentaje (89,1\%) que no tiene extra-edad fuerte, en cambio de los que abandonan hay un gran porcentaje (61,5\%) con extra-edad fuerte.


\newpage

En el gr?fico \ref{fig:eelyab} se va a relacionar la extra-edad leve de los alumnos con el abandono del sistema educativo p?blico.

%\begin{table}[htbp]
%	\centering
%	
%	\begin{tabular}{|c|c|c|c|}
%		\hline
%	\rowcolor[rgb]{ .776,  .878,  .706}	& No Abandona & Abandona & Poblaci?n total \\
%		\hline
%		Sin EE Leve & 68,3\% & 13,1\% & 65,0\% \\
%		\hline
%		Con EE Leve & 31,7\% & 86,9\% & 35,0\% \\
%		\hline
%		Total & 100,0\% & 100,0\% & 100,0\% \\
%		\hline
%	\end{tabular}%
%	\caption{Abandono seg?n Extra-edad Leve}
%	\label{tab:EELeve}%
%\end{table}%





\begin{figure}[H]
	\centering
	\includegraphics[width=0.5\linewidth]{EELyAb}
	\caption{Extra edad leve y abandono}
	\label{fig:eelyab}
\end{figure}


De los alumnos que no abandonan hay un gran porcentaje (68,3\%) que no tiene extra-edad leve, en cambio de los que abandonan hay un gran porcentaje (86,9\%) con extra-edad leve.




\newpage
En el gr?fico \ref{fig:inasistenciasrelativas} se muestra el gr?fico de densidad de las \textbf{inasistencias relativas} de los alumnos, recordar que la misma se calcula como el total de inasistencias del alumno sobre el total de veces que se le pas? la lista.

\begin{figure}[H]
	\centering
	\includegraphics[width=0.7\linewidth]{InasistenciasRelativas}
	\caption{Densidad de inasistencias relativas }
	\label{fig:inasistenciasrelativas}
\end{figure}

En este gr?fico de densidad se observa una gran masa de alumnos que tienen menos de 30\% de inasistencias relativas. Es decir, estos alumnos faltaron menos del 30\% del total de veces que le pasaron la lista.  

Menos del 10\% de los alumnos tienen m?s del 30\% de inasistencias relativas, para ver como es su relaci?n con el abandono, en la siguiente pagina se muestra un boxplot separando aquellos alumnos que abandonaron contra los que no lo hicieron.
\newpage
En el gr?fico \ref{fig:inasrel} se observan las inasistencias relativas para las dos poblaciones, de los alumnos que abandonan y de los que no. El \textit{boxplot} de la izquierda representa los alumnos que no abandonan el sistema educativo p?blico y el de la derecha los que si lo hacen.
\begin{figure}[H]
	\centering
	\includegraphics[width=0.7\linewidth]{Inas_rel}
	
	\caption{Inasistencias relativas seg?n abandono}
	\label{fig:inasrel}
\end{figure}
En el gr?fico se identifica claramente que los alumnos que abandonan tienen mayores porcentajes de inasistencias relativas. Es decir, la mitad de los alumnos que abandonan tienen entre un 22\% y un 43\% de inasistencias relativas. En cambio la mitad de los alumnos que no abandonan tienen entre un 1\% y un 10\% de inasistencias relativas


\newpage

	\section{Modelo log?stico de predicci?n}

Una vez realizado el an?lisis exploratorio de las variables y cada una de ellas con respecto a la variable dependiente se procede a realizar la experimentaci?n del modelo log?stico. 

\subsection{Metodolog?a}
Para establecer la relaci?n existente entre una variable dependiente Y, dicot?mica, y un conjunto de variables independientes $x=\left(x_{1},...,x_{k} \right)$ (que pueden ser tanto cualitativas como cuantitativas) se
puede ajustar una ecuaci?n de tal forma de que a trav?s de la estimaci?n de ciertos par?metros $\left(\beta_{0},\beta_{1},...,\beta_{k} \right)$ se prediga el comportamiento de Y \cite{L1}.

La variable respuesta $Y_{i}$ es una  \textit{variable aleatoria Bernulli}, con dos resultados posibles: \textit{exito o fracazo} codificados como $\left\lbrace 0,1\right\rbrace  $, los mismos tienen la siguiente distribuci?n: $P\left(Y_{i}=1\right)=\pi_{i}$, $P\left(Y_{i}=0\right)=1-\pi_{i}$, con esperanza	$ E\left(Y_{i}|X \right)=\pi_{i}$ .


%$$P\left(Y=1|X\right)=\pi=\frac{\exp^{\beta_{0}+\beta_{1}x_{1}+...+\beta_{k}x_{k} }}{1+\exp^{\beta_{0}+\beta_{1}x_{1}+...+\beta_{k}x_{k} }}$$

$$P\left(Y_{i}=1|X\right)=\pi_{i}=\frac{\exp^{\beta_{0}+\beta_{1}x_{1i}+...+\beta_{k}x_{ki} }}{1+\exp^{\beta_{0}+\beta_{1}x_{1i}+...+\beta_{k}x_{ki} }}$$


Dicho modelo puede ser linealizado mediante la transformaci?n $\log\left(\frac{\pi}{1-\pi} \right)$, la cu?l se denomina \textbf{transformaci?n logit}. El cociente $\frac{\pi}{1-\pi}$ se lo denomina \textbf{odds}, y es un cociente de probabilidades, la de ?xito sobre la de fracaso.\\

?Como se interpretan los \textbf{odds}?\\

Cuando se dice que los odds son 4 a 1 (odds=4) de que el alumno abandone el sistema educativo p?blico estamos diciendo que la probabilidad de que abandone es 0.8 ($4/5$).\\


%	En cambio cuando se dice que los odds de que un estudiante abandonde el sistema p?blico son de 1 a 3 (odds=1|3) estamos diciendo
%	que la probabilidad es 0.25.\\

Para estimar los par?metros $\beta$ del modelo se utiliza el m?todo de \textit{M?xima Verosimilitud}, buscando $\beta=\left(\beta_{1}...\beta_{p} \right) $ que maximice el logaritmo de la funci?n de verosimilitud, utilizando algoritmos de \textit{Newton-Raphson}.\\












\newpage
\subsection{Aplicaci?n del modelo}
En este estudio el objetivo es predecir si el alumno, que pertenece a primero de CES en el 2016, abandona el sistema educativo p?blico en 2017 o no. \textbf{Recordar que los mismos no necesariamente abandonan la educaci?n, puede ser que se anoten en el sistema privado. En este contexto cuando se menciona abandono se hace referencia al sistema educativo p?blico}.


Como se expuso en el cap?tulo \ref{cap3} la poblaci?n que se va a utilizar es aquellos alumnos que tengan una buena cobertura de pasaje de lista en linea. La misma est? compuesta por 28.232 alumnos, la cual se comporta de la siguiente manera:
\begin{itemize}
\item 26.566 alumnos (representados por el 94\% de la poblaci?n) que no abandonan el sistema educativo p?blico (0)

\item 1.666 alumnos (representados por el 6\% de la poblaci?n) que abandonan el sistema educativo p?blico (1)
\end{itemize}


\subsubsection{Variables a incluir en el modelo}

Luego de realizar el an?lisis exploratorio de las variables y la relaci?n que tiene cada una de ellas en el abandono, se exponen las mismas detallando su descripci?n y el recorrido que toman.


\begin{table}[H]
	\centering
	\begin{tabular}{|c|c|c|}
		\hline
		\rowcolor[rgb]{0.01, 0.28, 1.0}	Variable &  Descripci?n &   Recorrido \\
		\hline
		cl    & Cluster - contexto sociocultural del liceo en 1016 & 1,2,3,4,5\\
		\hline 	 		
		Sexo  & Sexo del alumno & F (femenino),M (masculino)  \\
		\hline 
		EE\_Fuerte & Si tiene m?s de un a?o m?s de la edad normativa & 1 (si tiene), 0(no tiene)\\
		\hline
		EE\_Leve & Si tiene un a?o m?s de la edad normativa & 1 (si tiene), 0(no tiene)\\
		\hline
		Abandona & Transici?n en la educaci?n p?blica 2016-2017 & 1(si abandona), 0(si no abandona) \\
		\hline
		inas\_rel & Cantidad de inasistencias sobre cobertura &  0,0 a 1,0. \\
		\hline
	\end{tabular}%
	\caption{Variables para incluir en el modelo}
	\label{variables}
\end{table}%

Luego se recodific? la variable cluster, el objetivo fue tener un recorrido mas acotado de la variable. Luego se va a evaluar como impacta en la \textit{performance} del modelo tener menos categor?as.\\


\begin{itemize}
\item Una forma de recodificaci?n fue separar en dos grupos. La variable se denomino \textbf{cl2} y se explica a continuaci?n:

\begin{itemize}
	\item Los cluster $\left\lbrace 1,2,3 \right\rbrace $ se agrupan en una categor?a que se llama \textbf{+crit}, en el que se identifican aquellos alumnos que provienen de escuelas de contexto sociocultural m?s cr?tico.
	
	\item Los cluster $\left\lbrace 4,5 \right\rbrace $ se agrupan en una categor?a que se llama \textbf{-crit}, en el que se identifican aquellos alumnos que provienen de escuelas de contexto sociocultural menos cr?tico.
\end{itemize}

\item La otra forma de recodificaci?n fue separar en tres grupos. La variable \textbf{cl3} se explica a continuaci?n.
\begin{itemize}
	\item Los cluster $\left\lbrace 1,2 \right\rbrace $ se agrupan en una categor?a que se llama \textbf{+crit}.
	
	\item El cluster $\left\lbrace 3 \right\rbrace $ queda solo en una categor?a que se llama \textbf{0crit}.
	
	
	\item Los cluster $\left\lbrace 4,5 \right\rbrace $ se agrupan en una categor?a que se llama \textbf{-crit}. 
\end{itemize}
\end{itemize}

\newpage
 

\subsubsection{Construcci?n del conjunto de entrenamiento}


Se va a dejar un 70\% del set de datos para entrenar el modelo y el 30\% restante para la validaci?n del modelo. La misma se hizo con un muestreo aleatorio simple sin reposici?n.


\begin{itemize}
\item La cantidad de alumnos que quedan en el conjunto de entrenamiento son 19.762, de los cuales:
\begin{itemize}
	\item 1.178  abandonan (el 6\%)
	\item 18.584 no abandonan (el 94\%)
\end{itemize}

\item La cantidad de alumnos que quedan en el conjunto de test son 8.470, de los cuales
\begin{itemize}
	\item 488 abandonan (el 6\%)
	\item 7.982 no abandonan (el 94\%)
\end{itemize}
\end{itemize}




\newpage
\subsection{Armado del los modelos}



\subsubsection{Modelo 1}
Se presenta en primer lugar la salida del resumen del modelo con todas las variables explicativas, obteniendo las estimaciones de los par?metros, las desviaciones est?ndar de los mismos, la distribuci?n \textit{z} y los p-valores.	

En el primer modelo se consideraron las siguientes variables X=inasistencias relativas, cluster, sexo y extra edad fuerte. 


\begin{table}[htbp]
	\centering
	
	\begin{tabular}{|c|c|c|c|c|c|}
		\hline
	\rowcolor[rgb]{0.01, 0.28, 1.0}	Coeficientes & Estimaci?n & Error std. & Valor z & $P(z>|z|)$ & Signif. \\
		\hline
		Intercepci?n & -4,14708 & 0,09302 & -44,58 & $<2,00E-16$ & *** \\
		\hline
		inas\_rel & 3,40618 & 0,16152 & 21,089 & $<2,00E-16$ & *** \\
		\hline
		cl2   & 0,11193 & 0,1207 & 0,927 & 0,3538 &  \\
		\hline
		cl3   & 0,48801 & 0,09372 & 5,207 & $<1,92E-07$ & *** \\
		\hline
		cl4   & -0,40947 & 0,21005 & -1,949 & 0,0512 & . \\
		\hline
		cl5   & 0,08448 & 0,09014 & 0,937 & 0,3486 &  \\
		\hline
		SexoM & 0,1228 & 0,06704 & 1,832 & 0,067 & . \\
		\hline
		EE\_Fuerte1 & 1,96389 & 0,07188 & 27,32 & $<2,00E-16$ & *** \\
		\hline
	\end{tabular}%
	\label{tab:Modelo1}%
	\caption{Resumen del \textbf{modelo 1} en el que se incluyen todas las variables menos extra edad leve. Se utiliza la variable cluster en su forma original}
\end{table}%


Las variables significativas con una confianza al 95\% seg?n el estad?stico de Wald en este modelo son:

\begin{itemize}
\item \textbf{inasistencias relativas}
\item \textbf{Cluster 3 al cu?l pertenece el liceo}
\item \textbf{extra-edad fuerte}  
\end{itemize} 

\subsubsection{Modelo 2}
Si en vez de utilizar la variable extra edad fuerte se utiliza la variable extra edad leve, el resumen del modelo es el siguiente:

\begin{table}[htbp]
	\centering
	\begin{tabular}{|c|c|c|c|c|c|}
		\hline
	\rowcolor[rgb]{0.01, 0.28, 1.0}	Coeficientes & Estimaci?n & Error std. & Valor z & $P(z>|z|)$ & Signif. \\
		\hline
		Intercepci?n & -4,80641 & 0,10954 & -43,878 & $<2,00E-16$ & *** \\
		\hline
		inas\_rel & 3,49542 & 0,1512 & 23,118 & $<2,00E-16$ & *** \\
		\hline
		cl2   & 0,10468 & 0,11708 & 0,894 & 0,371 &  \\
		\hline
		cl3   & 0,45889 & 0,09077 & 5,055 & $<4,30E-07$ & *** \\
		\hline
		cl4   & -0,33483 & 0,20687 & -1,619 & 0,106 &  \\
		\hline
		cl5   & 0,11131 & 0,08746 & 1,273 & 0,203 &  \\
		\hline
		SexoM & 0,06292 & 0,06579 & 0,956 & 0,339 &  \\
		\hline
		EE\_Leve1 & 2,09678 & 0,0914 & 22,94 & $<2,00E-16$ & *** \\
		\hline
	\end{tabular}%
	\label{tab:modelo2}%
		\caption{Resumen del \textbf{modelo 2} en el que se incluyen todas las variables menos extra edad fuerte. Se utiliza la variable cluster en su forma original}
\end{table}%
Las variables significativas son las mismas que en el \textbf{modelo 1}, solamente que se utiliza extra edad leve en vez de extra edad fuerte. 


\newpage
\subsubsection{Modelo 3}
En el siguiente modelo se utiliza la variable re-codificada para el cluster \textbf{cl2} en el que toma dos valores. Luego se presenta la salida del resumen del modelo con todas las variables explicativas, obteniendo las estimaciones de los par?metros, las desviaciones est?ndar de los mismos, la distribuci?n \textit{z} y los p-valores. 

En este \textbf{modelo 3} se consideraron las siguientes variables X=inasistencias relativas, \textbf{cl2} (en el que toma dos valores posibles), sexo y extra edad fuerte


% Table generated by Excel2LaTeX from sheet 'Hoja1'
\begin{table}[htbp]
	\centering
	\begin{tabular}{|c|c|c|c|c|c|}
		\hline
	\rowcolor[rgb]{0.01, 0.28, 1.0}	Coeficientes & Estimaci?n & Error std. & Valor z & $P(z>|z|)$ & Signif. \\
		\hline
		Intercepci?n & -4,12032 & 0,06271 & -65,703 & $< 2e-16$ & *** \\
		\hline
		inas\_rel & 3,46516 & 0,13441 & 25,781 & $< 2e-16$ & *** \\
		\hline
		cl2+crit & 0,17178 & 0,05854 & 2,934 & 0,00334 & ** \\
		\hline
		SexoM & 0,13534 & 0,05652 & 2,395 & 0,01664 & * \\
		\hline
		EE\_Fuerte1 & 1,94837 & 0,05998 & 32,484 & $< 2e-16$ & *** \\
		\hline
	\end{tabular}%
	\label{tab:model3}%
			\caption{Resumen del \textbf{modelo 3} en el que se incluyen todas las variables menos extra edad leve. Se utiliza la variable cluster en su forma recodificada como \textbf{cl2}}
\end{table}%


Se aprecia que todos los par?metros
estimados son significativos con una confianza mayor al 95 \%,
seg?n el estad?stico de Wald.\\

\subsubsection{Modelo 4}
En el siguiente modelo se prueba utilizar la variable re-codificada para el cluster \textbf{cl3} en el que toma tres valores. Luego se presenta la salida del resumen del modelo con todas las variables explicativas, obteniendo las estimaciones de los par?metros, las desviaciones est?ndar de los mismos, la distribuci?n \textit{z} y los p-valores. 

En este \textbf{modelo 4} se consideraron las siguientes variables X=inasistencias relativas, \textbf{cl3} (en el que toma dos valores posibles), sexo y extra edad fuerte

% Table generated by Excel2LaTeX from sheet 'Hoja1'
\begin{table}[htbp]
	\centering
	\begin{tabular}{|c|c|c|c|c|c|}
		\hline
	\rowcolor[rgb]{0.01, 0.28, 1.0}	Coeficientes & Estimaci?n & Error std. & Valor z & $P(z>|z|)$ & Signif. \\
		\hline
		Intercepci?n & -4,140107 & 0,063088 & -65,625 & $<2,00E-16$ & *** \\
		\hline
		inas\_rel & 3,529951 & 0,135458 & 26,059 & $<2,00E-16$ & *** \\
		\hline
		cl3+crit & 0,003955 & 0,067144 & 0,059 & 0,953 &  \\
		\hline
		cl30crit & 0,399365 & 0,070431 & 5,67  & $<1,43E-08$ & *** \\
		\hline
		SexoM & 0,131283 & 0,056606 & 2,319 & 0,0204 & * \\
		\hline
		EE\_Fuerte1 & 1,970298 & 0,060268 & 32,692 & $<2,00E-16$ & *** \\
		\hline
	\end{tabular}%
	\label{tab:model4}%
\caption{Resumen del \textbf{modelo 4} en el que se incluyen todas las variables menos extra edad leve. Se utiliza la variable cluster en su forma recodificada como \textbf{cl3}}
\end{table}%

Se aprecia que todos los par?metros
estimados son significativos con una confianza mayor al 95 \% (menos la variable \textbf{cl3}),
seg?n el estad?stico de Wald.\\

El modelo que se va a utilizar es el \textbf{modelo 3} en el que todas las variables son significativas, en la siguiente p?gina se va a realizar la validaci?n del mismo.

\newpage

\subsubsection{Validaci?n del modelo 3}

La significaci?n del modelo sirve para testear si el modelo es adecuado o no. Una prueba utilizada es la raz?n de verosimilitud del modelo. La misma se define como $\lambda=\dfrac{L_{R}}{L_{M}}$, donde $L_{M}$ es la verosimilitud del modelo completo $\frac{\exp^{\beta_{0}+\beta_{1}x_{1}+...+\beta_{p}x_{p} }}{1+\exp^{\beta_{0}+\beta_{1}x_{1}+...+\beta_{p}x_{p} }}$ y $L_{R}$ la del modelo reducido $\frac{\exp^{\beta_{0}+\beta_{1}x_{1}+...+\beta_{q}x_{q} }}{1+\exp^{\beta_{0}+\beta_{1}x_{1}+...+\beta_{q}x_{q} }}$, donde $p>q$.


$$H_{0})\beta_{1}=\beta_{2}=...=\beta_{p}=0$$

$$H_{1}) \text{alg?n} \; \beta_{k}\neq 0, \; k=1,2,...,p $$


$-2\log(\lambda)$ se distribuye $\chi^2_{(p+1-q)},\alpha$, siendo (p+1) y q la cantidad de par?metros incluidos en el modelo completo y el modelo reducido respectivamente.\\

\textbf{\textit{Test de raz?n de verosimilitud}}
$$ -2\log(\lambda)=-2\log(\dfrac{L_{R}}{L_{M}})=-2\left(  \log L_{R}-\log L_{M}\right)$$ 

La hip?tesis nula ser? rechazada para el nivel de significaci?n $\alpha$ cuando $-2\log(\lambda)>\chi^2_{(p+1-q)},\alpha$. Esto es equivalente a que el p valor del contraste sea menor que el nivel de significaci?n fijado \cite{L1}.\\
 

Para este \textbf{modelo 3} el \textit{Test de raz?n de verosimilitud} indica que el modelo es significativo, seg?n el valor de la tabla de una $\chi^2_{(p+1-q)},0.05$ el p-valor devuelto es muy peque?o. Esto se puede apreciar en la siguiente salida:

% Table generated by Excel2LaTeX from sheet 'Hoja1'
\begin{table}[htbp]
	\centering
	
	\begin{tabular}{|c|c|c|c|c|c|c|}
		\hline
	\rowcolor[rgb]{ .776,  .878,  .706}	& Df    & Deviance & Resid. Df & Resid. Dev & $Pr(>Chi)$ & Signif. \\
		\hline
		Modelo nulo &       &  & 28231 &    12661,4   &       &  \\
		\hline
		inas\_rel & 1     & 1828,18 & 28230 & 1,08E+04 & 2,20E-16 & *** \\
		\hline
		cl2   & 1     & 23,15 & 28229 & 10810 & 1,50E-06 & *** \\
		\hline
		Sexo  & 1     & 18,55 & 28228 & 10791,5 & 1,66E-05 & *** \\
		\hline
		EE\_Fuerte & 1     & 1022,13 & 28227 & 9769,4 & 2,20E-16 & *** \\
		\hline
	\end{tabular}%
	\label{tab:vero}%
	\caption{Test de raz?n de verosimilitud del modelo 3}
\end{table}%





Las variables que van a quedar en el modelo son las siguientes:

\begin{itemize}
	\item \textbf{inas\_rel}: inasistencias relativas
	\item \textbf{cl2}: el cluster en el que est? el liceo, con la variable recodificada que toma los valores \textbf{+crit} y \textbf{-crit}
	\item \textbf{Sexo} del alumno
	\item \textbf{EE\_Fuerte:} en el que toma el valor uno en el caso de que el alumno tenga m?s de un a?o de la edad normativa para la generaci?n que est? en 2016
\end{itemize}

\newpage
\subsection{Par?metros del modelo e interpretaci?n}

A continuaci?n se realizar? una descripci?n e interpretaci?n detallada de los par?metros del modelo elegido. 

Los par?metros del modelo son $\beta_{0}$, la ordenada en el origen, y $\left\lbrace \beta_{1},...,\beta_{p} \right\rbrace$, las pendientes. A veces se utilizan tambi?n como par?metros $exp(\beta_{0})$ y $exp(\beta_{i})$, que se denominan los odd ratios o ratios de probabilidades, e indican cuanto se modifican las probabilidades por unidad de cambio en las variables x \cite{L2}.

$$O_{i}=\frac{p_{i}}{1-p_{i}}=exp(\beta_{0})*\prod_{j=1}^{p} exp(\beta_{i})^{x_{j}} $$

Suponiendo que dos elementos ,i,k, con todos los valores de las variables iguales excepto la variable h y $x_{ih}=x_{ih}+1$. El cociente de los ratios de probabilidades (odds ratio) para estas dos observaciones es:

$$\frac{O_{i}}{O_{k}}=\exp^{\beta_{h}}     $$

Dicha igualdad indica cuanto se modifica el ratio de probabilidades cuando la variable $x_{h}$ aumenta una unidad.



\subsubsection{Interpretaci?n}


Para la interpretaci?n de los par?metros del modelo, se realizan los siguientes calculos:

\begin{enumerate}
	\item \textbf{T?rmino independiente}.\\
	El t?rmino independiente en el modelo de regresi?n log?stica es el siguiente:
	\begin{table}[H]
		\centering
		\begin{tabular}{|c|c|}
			\hline 
			\rowcolor[rgb]{ 1.0,  0.01,  .24}	\textbf{$\hat{\beta_{0}}$}  & $Exp(\hat{\beta_{0}})$  \\ 
			\hline 
			-4.12	& 0.016  \\ 
			\hline 
		\end{tabular} 
		\caption{T?rmino independiente}
	\end{table}
	
	\item \textbf{Inasistencias relativas.}\\
	
	Esta variable es la proporci?n de inasistencias del alumno en los d?as que le pasaron lista. El par?metro asignado a esta variable es:
	
	\begin{table}[H]
		\centering
		\begin{tabular}{|c|c|}
			\hline 
			\rowcolor[rgb]{ 1.0,  0.01,  .24}		\textbf{$\hat{\beta_{1}}$}  & $Exp(\hat{\beta_{1}})$  \\ 
			\hline 
			3.46	& 31.82  \\ 
			\hline 
		\end{tabular} 
		\caption{Estimaci?n del par?metro inasistencias relativas}
	\end{table}	
	
	Al aumentar las inasistencias relativas, dejando todas los dem?s valores constantes, el \textit{odd} ratio de Abandonar aumenta.
	Si aumenta en una unidad las inasistencias relativas, manteniendo las dem?s constantes la probabilidad de abandonar es 32 veces m?s grande que la de no abandonar.
	
	\item \textbf{Cluster 2.}\\
	El cluster en el que est? el liceo se divide en dos categor?as. El grupo \textbf{-crit} que es compuesto por liceos que se componen por alumnos que provienen de escuelas de los quintiles m?s favorables. El grupo \textbf{+crit} que es compuesto por liceos que se componen por alumnos que provienen de escuelas menos favorables, el valor del par?metro se imprime en el cuadro \ref{ECont}.
	
	\begin{table}[H]
		\centering
		\begin{tabular}{|c|c|}
			\hline 
			\rowcolor[rgb]{ 1.0,  0.01,  .24}		\textbf{$\hat{\beta_{2}}$}  & $Exp(\hat{\beta_{2}})$  \\ 
			\hline 
			0.17	& 1.19  \\ 
			\hline 
		\end{tabular} 
		\caption{Estimaci?n del par?metro cluster 2}
		\label{ECont}
	\end{table}
	Si el alumno pertenece al cluster \textbf{+crit} aumenta el odd ratio de abandonar el sistema con respecto al \textbf{-crit}, dejando el resto de las variables constantes.
	
	\item \textbf{Sexo}\\
	El peso asignado a la categoria masculino es:
	\begin{table}[H]
		\centering
		\begin{tabular}{|c|c|}
			\hline 
			\rowcolor[rgb]{ 1.0,  0.01,  .24}			\textbf{$\hat{\beta_{3}}$}  & $Exp(\hat{\beta_{3}})$  \\ 
			\hline 
			0.14	& 1.15  \\ 
			\hline 
		\end{tabular} 
		\caption{Estimaci?n del par?metro Sexo }
	\end{table}
	
	El sexo masculino aumenta el odd ratio de abandonar el sistema educativo p?blico con respecto al femenino, dejando el resto de los valores constantes.
	
	\item \textbf{Extra-edad Fuerte}.\\
	
	El peso asignado a la categoria que tiene extra-edad fuerte es:
	\begin{table}[H]
		\centering
		\begin{tabular}{|c|c|}
			\hline 
			\rowcolor[rgb]{ 1.0,  0.01,  .24}	\textbf{$\hat{\beta_{3}}$}  & $Exp(\hat{\beta_{3}})$  \\ 
			\hline 
			1.94	& 6.96  \\ 
			\hline 
		\end{tabular} 
		\caption{Estimaci?n del par?metro extra-edad fuerte}
	\end{table}
	
	Tener extra edad leve aumenta el odd ratio de abandonar el sistema educativo p?blico con respecto a no tener, dejando el resto de los valores constantes.
	
	
\end{enumerate}











\newpage
\subsection{Variable Predictora}

Predecir el valor de la variable de respuesta, en funci?n de ciertos valores de
las variables explicativas, implica determinar cual es el valor cr?tico a partir del cual las estimaciones del valor esperado implican un valor de 1 para la variable de respuesta. 


Valores grandes de $\pi_{i}$ implican $Y_{i} = 1$ mientras que valores chicos
de $\pi_{i}$ implican $Y_{i} = 0$. 

El problema a abordar es determinar cuando una estimaci?n es considerada un valor muy grande o muy chico. 

% Existen distintas aproximaciones a tener en cuenta para determinar el punto de corte, las mismas se van a 
% detallar en la subsecci?n siguiente.\\
	



\subsection{Evaluaci?n del punto de corte}
Para la evaluaci?n del punto de corte se van a evaluar distintas m?tricas. Las mismas son utilizadas para evaluar la exactitud y la capacidad de predicci?n del modelo. Es decir evaluar cu?ntos objetos se etiquetaron correctamente y cu?ntos no. Se definen las siguientes situaciones que pueden ocurrir en el proceso de clasificaci?n:


\begin{itemize}
	\item \textbf{Verdaderos positivos}. Un verdadero positivo es un alumno que abandon? y es clasificado correctamente por el modelo.
	\item \textbf{Falsos positivos}. Un falso positivo consiste en un alumno que no abandono, pero el modelo lo clasific? como que va a abandonar.
	\item \textbf{Verdaderos negativos}.  Un verdadero negativo es un alumno que no abandona y el modelo lo clasifica correctamente.
	\item \textbf{Falsos negativos}.Un falso negativo es un alumno que abandona pero el modelo lo clasifica como que no.
\end{itemize}

Utilizando las definiciones mencionadas anteriormente; el clasificador puede ser evaluado con las siguiente m?tricas:


 $$Ratio \; de \; Verdaderos \; Positivos= \frac{ Positivos \; clasificados \; correctamente}{Total \; de \; positivos} $$ 


 $$Ratio \; de \; Falsos \; Positivos= \frac{ Positivos \; clasificados \; incorrectamente}{Total \; de \; negativos} $$ 










\newpage
\subsection{Desempe?o del clasificador}

Una forma de evaluar la calidad de ajuste de un modelo es utilizando la
curva ROC (Receiver Operating Characteristic), que capta las caracter?sticas
del funcionamiento del modelo a trav?s de la variaci?n de su comportamiento.


En la curva ROC se grafica el ratio de verdaderos positivos en el eje de las abscisas y el ratio de falsos positivos en el eje de las ordenadas, seg?n diferentes puntos de corte.


En la figura \ref{fig:roc} se hace una curva ROC para evaluar el mejor punto de corte utilizando el conjunto de datos de test:
\begin{figure}[H]
	\centering
	\includegraphics[width=0.5\linewidth]{ROC}
	\caption{curva ROC}
	\label{fig:roc}
\end{figure}


En el siguiente cuadro se imprimen los valores del ratio de verdaderos positivos (TP) y ratio de falsos positivos (FP) seg?n distintos puntos de corte.


\begin{table}[H]
	\centering

	\begin{tabular}{|c|c|c|}
		\hline
		Punto de corte & Ratio de TP & Ratio de FP \\
		\hline
		0,77  & 0,00  & 0,00 \\
		\hline
		.     & .     & . \\
		\hline
		0,11  & 0,67  & 0,12 \\
		\hline
		0,10  & 0,67  & 0,12 \\
		\hline
		0,09  & 0,69  & 0,12 \\
		\hline
		0,08  & 0,70  & 0,12 \\
		\hline
		0,07  & 0,71  & 0,13 \\
		\hline
		0,06  & 0,74  & 0,14 \\
		\hline
		0,05  & 0,77  & 0,15 \\
		\hline
\rowcolor[rgb]{0.87, 0.36, 0.51}		0,04  & 0,81  & 0,18 \\
		\hline
		0,03  & 0,89  & 0,32 \\
		\hline
		0,02  & 1,00  & 0,93 \\
		\hline
	\end{tabular}%
	\label{tab:addlabel}%
		\caption{Punto de corte ?ptimo ultimos 10 valores}
\end{table}%




\newpage
\section{Conclusiones}
El mejor desempe?o se tiene con un punto de corte igual a 0,04. El desempe?o del clasificador es el siguiente:


% Table generated by Excel2LaTeX from sheet 'Hoja1'
\begin{table}[H]
	\centering

	\begin{tabular}{|c|c|c|c|}
		\hline
	\rowcolor[rgb]{0.87, 0.36, 0.51}	& Realidad no abanona & Realidad abandona & Total \\
		\hline
	\cellcolor[rgb]{0.87, 0.36, 0.51}	Predicci?n no abandona & 6695  & 103   & 6798 \\
		\hline
	\cellcolor[rgb]{0.87, 0.36, 0.51}	Predicci?n abandona & 1287  & 385   & 1672 \\
		\hline
	\cellcolor[rgb]{0.87, 0.36, 0.51}	Total & 7982  & 488   & 8470 \\
		\hline
	\end{tabular}%
	\label{tab:addlabel}%
		\caption{Desempe?o del clasificador}
\end{table}%

%Como se puede observar con este punto de corte la cantidad de verdaderos positivos es 385 de un total de 488, por lo que el ratio de verdaderos positivos es $RTP=385/488=0,80$ y el ratio de falsos positivos es $RFP=1.287/7.982=0,18$.\\ 
%
%
%Es decir seg?n el conjunto de test compuesto por 8.470 alumnos, hay 488 alumnos que abandonaron y el modelo le acert? a 385 (a un 80\%). De los 7.982 que no abandonan el modelo le erro a 1.287 (a un 18\%) prediciendo como que iban a abandonar. 


En el conjunto de test que tiene 8.470 alumnos:

\begin{itemize}

\item hay 488 alumnos que abandonaron el sistema educativo p?blico. El modelo predijo que 385 iban a abandonar, es decir le acert? a un 80\%

\item De los 7.982 alumnos que no abandonaron el sistema educativo p?blico el modelo acert? a 6.695 y clasifico incorrectamente a 1.287 (18\%) identific?ndolos como que van a abandonar el sistema  

\end{itemize}





\newpage



\begin{thebibliography}{9}
	\bibitem{L1} \textsc{Jorge Blanco}
	\textit{Introducci?n al analisis de datos multivariados}
	
	
	\bibitem{L2}\textsc{Da?el Pe?a}
	\textit{AN?LISIS DE DATOS MULTIVARIANTES}, 23 de enero de 2002.
\end{thebibliography}





	

	\cellcolor[rgb]{0.87, 0.36, 0.51}	Predicci?n no abandona & 6695  & 103   & 6798 \\
		\hline
	\cellcolor[rgb]{0.87, 0.36, 0.51}	Predicci?n abandona & 1287  & 385   & 1672 \\
		\hline
	\cellcolor[rgb]{0.87, 0.36, 0.51}	Total & 7982  & 488   & 8470 \\
		\hline
	\end{tabular}%
	\label{tab:addlabel}%
		\caption{Desempe?o del clasificador}
\end{table}%

%Como se puede observar con este punto de corte la cantidad de verdaderos positivos es 385 de un total de 488, por lo que el ratio de verdaderos positivos es $RTP=385/488=0,80$ y el ratio de falsos positivos es $RFP=1.287/7.982=0,18$.\\ 
%
%
%Es decir seg?n el conjunto de test compuesto por 8.470 alumnos, hay 488 alumnos que abandonaron y el modelo le acert? a 385 (a un 80\%). De los 7.982 que no abandonan el modelo le erro a 1.287 (a un 18\%) prediciendo como que iban a abandonar. 


En el conjunto de test que tiene 8.470 alumnos:

\begin{itemize}

\item hay 488 alumnos que abandonaron el sistema educativo p?blico. El modelo predijo que 385 iban a abandonar, es decir le acert? a un 80\%

\item De los 7.982 alumnos que no abandonaron el sistema educativo p?blico el modelo acert? a 6.695 y clasifico incorrectamente a 1.287 (18\%) identific?ndolos como que van a abandonar el sistema  

\end{itemize}





\newpage



\begin{thebibliography}{9}
	\bibitem{L1} \textsc{Jorge Blanco}
	\textit{Introducci?n al analisis de datos multivariados}
	
	
	\bibitem{L2}\textsc{Da?el Pe?a}
	\textit{AN?LISIS DE DATOS MULTIVARIANTES}, 23 de enero de 2002.
\end{thebibliography}





	



\end{document}